// Code generated by Fern. DO NOT EDIT.

package client

import (
	accounts "github.com/voltariafinance/go-sdk/v2/accounts"
	clients "github.com/voltariafinance/go-sdk/v2/clients"
	core "github.com/voltariafinance/go-sdk/v2/core"
	documents "github.com/voltariafinance/go-sdk/v2/documents"
	drawdowns "github.com/voltariafinance/go-sdk/v2/drawdowns"
	installments "github.com/voltariafinance/go-sdk/v2/installments"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	investors "github.com/voltariafinance/go-sdk/v2/investors"
	loans "github.com/voltariafinance/go-sdk/v2/loans"
	option "github.com/voltariafinance/go-sdk/v2/option"
	partners "github.com/voltariafinance/go-sdk/v2/partners"
	repayments "github.com/voltariafinance/go-sdk/v2/repayments"
	sandbox "github.com/voltariafinance/go-sdk/v2/sandbox"
	webhooks "github.com/voltariafinance/go-sdk/v2/webhooks"
)

type Client struct {
	Clients      *clients.Client
	Sandbox      *sandbox.Client
	Accounts     *accounts.Client
	Documents    *documents.Client
	Investors    *investors.Client
	Installments *installments.Client
	Loans        *loans.Client
	Partners     *partners.Client
	Webhooks     *webhooks.Client
	Repayments   *repayments.Client
	Drawdowns    *drawdowns.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Clients:      clients.NewClient(options),
		Sandbox:      sandbox.NewClient(options),
		Accounts:     accounts.NewClient(options),
		Documents:    documents.NewClient(options),
		Investors:    investors.NewClient(options),
		Installments: installments.NewClient(options),
		Loans:        loans.NewClient(options),
		Partners:     partners.NewClient(options),
		Webhooks:     webhooks.NewClient(options),
		Repayments:   repayments.NewClient(options),
		Drawdowns:    drawdowns.NewClient(options),
		options:      options,
		baseURL:      options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
