// Code generated by Fern. DO NOT EDIT.

package accounts

import (
	context "context"
	http "net/http"

	v2 "github.com/voltariafinance/go-sdk/v2"
	core "github.com/voltariafinance/go-sdk/v2/core"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	option "github.com/voltariafinance/go-sdk/v2/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) ListClientAccountFields(
	ctx context.Context,
	request *v2.ListClientAccountFieldsRequest,
	opts ...option.RequestOption,
) (*core.Response[map[string]*v2.CurrencyFieldSpec], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/clients/%v/accounts/fields",
		request.ClientID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response map[string]*v2.CurrencyFieldSpec
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[map[string]*v2.CurrencyFieldSpec]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListClientAccounts(
	ctx context.Context,
	request *v2.ListClientAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[*v2.PaginatedResponseClientAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/clients/%v/accounts",
		request.ClientID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *v2.PaginatedResponseClientAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.PaginatedResponseClientAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateClientAccount(
	ctx context.Context,
	request *v2.PartnerClientAccountCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*v2.ClientAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/clients/%v/accounts",
		request.ClientID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *v2.ClientAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.ClientAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetClientAccount(
	ctx context.Context,
	request *v2.GetClientAccountRequest,
	opts ...option.RequestOption,
) (*core.Response[*v2.ClientAccountResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/clients/%v/accounts/%v",
		request.ClientID,
		request.AccountID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *v2.ClientAccountResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.ClientAccountResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
