// Code generated by Fern. DO NOT EDIT.

package recoveries

import (
	context "context"

	v2 "github.com/voltariafinance/go-sdk/v2"
	core "github.com/voltariafinance/go-sdk/v2/core"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	option "github.com/voltariafinance/go-sdk/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve recoveries recorded against your loans. Supports filtering by client or loan.
func (c *Client) ListRecoveries(
	ctx context.Context,
	request *v2.ListRecoveriesRequest,
	opts ...option.RequestOption,
) (*v2.PaginatedResponseRecoveryResponse, error) {
	response, err := c.WithRawResponse.ListRecoveries(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Record a new recovery against one of your loans.
func (c *Client) CreateRecovery(
	ctx context.Context,
	request *v2.RecoveryCreatePayload,
	opts ...option.RequestOption,
) (*v2.RecoveryResponse, error) {
	response, err := c.WithRawResponse.CreateRecovery(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
