// Code generated by Fern. DO NOT EDIT.

package sandbox

import (
	context "context"

	v2 "github.com/voltariafinance/go-sdk/v2"
	core "github.com/voltariafinance/go-sdk/v2/core"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	option "github.com/voltariafinance/go-sdk/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Update an existing client's status or credit limit using their client ID.
func (c *Client) UpdateClient(
	ctx context.Context,
	request *v2.ClientUpdateSandbox,
	opts ...option.RequestOption,
) (*v2.ClientResponse, error) {
	response, err := c.WithRawResponse.UpdateClient(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update the status of a specific loan using its unique loan ID.
func (c *Client) UpdateLoan(
	ctx context.Context,
	request *v2.LoanUpdateSandbox,
	opts ...option.RequestOption,
) (*v2.LoanResponseWithInstallments, error) {
	response, err := c.WithRawResponse.UpdateLoan(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Test a webhook subscription by ID or trigger all by event type.
func (c *Client) WebhookTest(
	ctx context.Context,
	request *v2.WebhookTestSandbox,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.WebhookTest(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
