// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersDeleteDocumentRequest(t *testing.T) {
	t.Run("SetDocumentID", func(t *testing.T) {
		obj := &DeleteDocumentRequest{}
		var fernTestValueDocumentID string
		obj.SetDocumentID(fernTestValueDocumentID)
		assert.Equal(t, fernTestValueDocumentID, obj.DocumentID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDeleteDocumentRequest(t *testing.T) {
	t.Run("SetDocumentID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteDocumentRequest{}
		var fernTestValueDocumentID string

		// Act
		obj.SetDocumentID(fernTestValueDocumentID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetDocumentByIDRequest(t *testing.T) {
	t.Run("SetDocumentID", func(t *testing.T) {
		obj := &GetDocumentByIDRequest{}
		var fernTestValueDocumentID string
		obj.SetDocumentID(fernTestValueDocumentID)
		assert.Equal(t, fernTestValueDocumentID, obj.DocumentID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetDocumentByIDRequest(t *testing.T) {
	t.Run("SetDocumentID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetDocumentByIDRequest{}
		var fernTestValueDocumentID string

		// Act
		obj.SetDocumentID(fernTestValueDocumentID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListDocumentsRequest(t *testing.T) {
	t.Run("SetClientID", func(t *testing.T) {
		obj := &ListDocumentsRequest{}
		var fernTestValueClientID *string
		obj.SetClientID(fernTestValueClientID)
		assert.Equal(t, fernTestValueClientID, obj.ClientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLoanID", func(t *testing.T) {
		obj := &ListDocumentsRequest{}
		var fernTestValueLoanID *string
		obj.SetLoanID(fernTestValueLoanID)
		assert.Equal(t, fernTestValueLoanID, obj.LoanID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetInstallmentID", func(t *testing.T) {
		obj := &ListDocumentsRequest{}
		var fernTestValueInstallmentID *string
		obj.SetInstallmentID(fernTestValueInstallmentID)
		assert.Equal(t, fernTestValueInstallmentID, obj.InstallmentID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWaterfallID", func(t *testing.T) {
		obj := &ListDocumentsRequest{}
		var fernTestValueWaterfallID *string
		obj.SetWaterfallID(fernTestValueWaterfallID)
		assert.Equal(t, fernTestValueWaterfallID, obj.WaterfallID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &ListDocumentsRequest{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPageSize", func(t *testing.T) {
		obj := &ListDocumentsRequest{}
		var fernTestValuePageSize *int
		obj.SetPageSize(fernTestValuePageSize)
		assert.Equal(t, fernTestValuePageSize, obj.PageSize)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrderBy", func(t *testing.T) {
		obj := &ListDocumentsRequest{}
		var fernTestValueOrderBy *string
		obj.SetOrderBy(fernTestValueOrderBy)
		assert.Equal(t, fernTestValueOrderBy, obj.OrderBy)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQ", func(t *testing.T) {
		obj := &ListDocumentsRequest{}
		var fernTestValueQ *string
		obj.SetQ(fernTestValueQ)
		assert.Equal(t, fernTestValueQ, obj.Q)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListDocumentsRequest(t *testing.T) {
	t.Run("SetClientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDocumentsRequest{}
		var fernTestValueClientID *string

		// Act
		obj.SetClientID(fernTestValueClientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLoanID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDocumentsRequest{}
		var fernTestValueLoanID *string

		// Act
		obj.SetLoanID(fernTestValueLoanID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetInstallmentID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDocumentsRequest{}
		var fernTestValueInstallmentID *string

		// Act
		obj.SetInstallmentID(fernTestValueInstallmentID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWaterfallID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDocumentsRequest{}
		var fernTestValueWaterfallID *string

		// Act
		obj.SetWaterfallID(fernTestValueWaterfallID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDocumentsRequest{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPageSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDocumentsRequest{}
		var fernTestValuePageSize *int

		// Act
		obj.SetPageSize(fernTestValuePageSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrderBy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDocumentsRequest{}
		var fernTestValueOrderBy *string

		// Act
		obj.SetOrderBy(fernTestValueOrderBy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQ_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDocumentsRequest{}
		var fernTestValueQ *string

		// Act
		obj.SetQ(fernTestValueQ)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersAvailableDocumentCategoriesResponse(t *testing.T) {
	t.Run("SetCategories", func(t *testing.T) {
		obj := &AvailableDocumentCategoriesResponse{}
		var fernTestValueCategories []string
		obj.SetCategories(fernTestValueCategories)
		assert.Equal(t, fernTestValueCategories, obj.Categories)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersAvailableDocumentCategoriesResponse(t *testing.T) {
	t.Run("GetCategories", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AvailableDocumentCategoriesResponse{}
		var expected []string
		obj.Categories = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCategories(), "getter should return the property value")
	})

	t.Run("GetCategories_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AvailableDocumentCategoriesResponse{}
		obj.Categories = nil

		// Act & Assert
		assert.Nil(t, obj.GetCategories(), "getter should return nil when property is nil")
	})

	t.Run("GetCategories_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AvailableDocumentCategoriesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCategories() // Should return zero value
	})

}

func TestSettersMarkExplicitAvailableDocumentCategoriesResponse(t *testing.T) {
	t.Run("SetCategories_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AvailableDocumentCategoriesResponse{}
		var fernTestValueCategories []string

		// Act
		obj.SetCategories(fernTestValueCategories)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDocumentResponse(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &DocumentResponse{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCategory", func(t *testing.T) {
		obj := &DocumentResponse{}
		var fernTestValueCategory string
		obj.SetCategory(fernTestValueCategory)
		assert.Equal(t, fernTestValueCategory, obj.Category)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFileName", func(t *testing.T) {
		obj := &DocumentResponse{}
		var fernTestValueFileName string
		obj.SetFileName(fernTestValueFileName)
		assert.Equal(t, fernTestValueFileName, obj.FileName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFileType", func(t *testing.T) {
		obj := &DocumentResponse{}
		var fernTestValueFileType string
		obj.SetFileType(fernTestValueFileType)
		assert.Equal(t, fernTestValueFileType, obj.FileType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetClientID", func(t *testing.T) {
		obj := &DocumentResponse{}
		var fernTestValueClientID *string
		obj.SetClientID(fernTestValueClientID)
		assert.Equal(t, fernTestValueClientID, obj.ClientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFileURL", func(t *testing.T) {
		obj := &DocumentResponse{}
		var fernTestValueFileURL *string
		obj.SetFileURL(fernTestValueFileURL)
		assert.Equal(t, fernTestValueFileURL, obj.FileURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLoanID", func(t *testing.T) {
		obj := &DocumentResponse{}
		var fernTestValueLoanID *string
		obj.SetLoanID(fernTestValueLoanID)
		assert.Equal(t, fernTestValueLoanID, obj.LoanID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetInstallmentID", func(t *testing.T) {
		obj := &DocumentResponse{}
		var fernTestValueInstallmentID *string
		obj.SetInstallmentID(fernTestValueInstallmentID)
		assert.Equal(t, fernTestValueInstallmentID, obj.InstallmentID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFolderPath", func(t *testing.T) {
		obj := &DocumentResponse{}
		var fernTestValueFolderPath *string
		obj.SetFolderPath(fernTestValueFolderPath)
		assert.Equal(t, fernTestValueFolderPath, obj.FolderPath)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocumentDate", func(t *testing.T) {
		obj := &DocumentResponse{}
		var fernTestValueDocumentDate *time.Time
		obj.SetDocumentDate(fernTestValueDocumentDate)
		assert.Equal(t, fernTestValueDocumentDate, obj.DocumentDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExpiryDate", func(t *testing.T) {
		obj := &DocumentResponse{}
		var fernTestValueExpiryDate *time.Time
		obj.SetExpiryDate(fernTestValueExpiryDate)
		assert.Equal(t, fernTestValueExpiryDate, obj.ExpiryDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &DocumentResponse{}
		var fernTestValueCreatedAt time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersDocumentResponse(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var expected string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetCategory", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var expected string
		obj.Category = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCategory(), "getter should return the property value")
	})

	t.Run("GetCategory_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCategory() // Should return zero value
	})

	t.Run("GetFileName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var expected string
		obj.FileName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFileName(), "getter should return the property value")
	})

	t.Run("GetFileName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFileName() // Should return zero value
	})

	t.Run("GetFileType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var expected string
		obj.FileType = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFileType(), "getter should return the property value")
	})

	t.Run("GetFileType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFileType() // Should return zero value
	})

	t.Run("GetClientID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var expected *string
		obj.ClientID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetClientID(), "getter should return the property value")
	})

	t.Run("GetClientID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		obj.ClientID = nil

		// Act & Assert
		assert.Nil(t, obj.GetClientID(), "getter should return nil when property is nil")
	})

	t.Run("GetClientID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetClientID() // Should return zero value
	})

	t.Run("GetFileURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var expected *string
		obj.FileURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFileURL(), "getter should return the property value")
	})

	t.Run("GetFileURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		obj.FileURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetFileURL(), "getter should return nil when property is nil")
	})

	t.Run("GetFileURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFileURL() // Should return zero value
	})

	t.Run("GetLoanID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var expected *string
		obj.LoanID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLoanID(), "getter should return the property value")
	})

	t.Run("GetLoanID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		obj.LoanID = nil

		// Act & Assert
		assert.Nil(t, obj.GetLoanID(), "getter should return nil when property is nil")
	})

	t.Run("GetLoanID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLoanID() // Should return zero value
	})

	t.Run("GetInstallmentID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var expected *string
		obj.InstallmentID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetInstallmentID(), "getter should return the property value")
	})

	t.Run("GetInstallmentID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		obj.InstallmentID = nil

		// Act & Assert
		assert.Nil(t, obj.GetInstallmentID(), "getter should return nil when property is nil")
	})

	t.Run("GetInstallmentID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetInstallmentID() // Should return zero value
	})

	t.Run("GetFolderPath", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var expected *string
		obj.FolderPath = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFolderPath(), "getter should return the property value")
	})

	t.Run("GetFolderPath_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		obj.FolderPath = nil

		// Act & Assert
		assert.Nil(t, obj.GetFolderPath(), "getter should return nil when property is nil")
	})

	t.Run("GetFolderPath_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFolderPath() // Should return zero value
	})

	t.Run("GetDocumentDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var expected *time.Time
		obj.DocumentDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDocumentDate(), "getter should return the property value")
	})

	t.Run("GetDocumentDate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		obj.DocumentDate = nil

		// Act & Assert
		assert.Nil(t, obj.GetDocumentDate(), "getter should return nil when property is nil")
	})

	t.Run("GetDocumentDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDocumentDate() // Should return zero value
	})

	t.Run("GetExpiryDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var expected *time.Time
		obj.ExpiryDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExpiryDate(), "getter should return the property value")
	})

	t.Run("GetExpiryDate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		obj.ExpiryDate = nil

		// Act & Assert
		assert.Nil(t, obj.GetExpiryDate(), "getter should return nil when property is nil")
	})

	t.Run("GetExpiryDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExpiryDate() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var expected time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

}

func TestSettersMarkExplicitDocumentResponse(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCategory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var fernTestValueCategory string

		// Act
		obj.SetCategory(fernTestValueCategory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFileName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var fernTestValueFileName string

		// Act
		obj.SetFileName(fernTestValueFileName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFileType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var fernTestValueFileType string

		// Act
		obj.SetFileType(fernTestValueFileType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetClientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var fernTestValueClientID *string

		// Act
		obj.SetClientID(fernTestValueClientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFileURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var fernTestValueFileURL *string

		// Act
		obj.SetFileURL(fernTestValueFileURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLoanID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var fernTestValueLoanID *string

		// Act
		obj.SetLoanID(fernTestValueLoanID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetInstallmentID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var fernTestValueInstallmentID *string

		// Act
		obj.SetInstallmentID(fernTestValueInstallmentID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFolderPath_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var fernTestValueFolderPath *string

		// Act
		obj.SetFolderPath(fernTestValueFolderPath)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocumentDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var fernTestValueDocumentDate *time.Time

		// Act
		obj.SetDocumentDate(fernTestValueDocumentDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExpiryDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var fernTestValueExpiryDate *time.Time

		// Act
		obj.SetExpiryDate(fernTestValueExpiryDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}
		var fernTestValueCreatedAt time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPaginatedResponseDocumentResponse(t *testing.T) {
	t.Run("SetItems", func(t *testing.T) {
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValueItems []*DocumentResponse
		obj.SetItems(fernTestValueItems)
		assert.Equal(t, fernTestValueItems, obj.Items)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPageSize", func(t *testing.T) {
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValuePageSize *int
		obj.SetPageSize(fernTestValuePageSize)
		assert.Equal(t, fernTestValuePageSize, obj.PageSize)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetItemsInPage", func(t *testing.T) {
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValueItemsInPage *int
		obj.SetItemsInPage(fernTestValueItemsInPage)
		assert.Equal(t, fernTestValueItemsInPage, obj.ItemsInPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTotalItems", func(t *testing.T) {
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValueTotalItems *int
		obj.SetTotalItems(fernTestValueTotalItems)
		assert.Equal(t, fernTestValueTotalItems, obj.TotalItems)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTotalPages", func(t *testing.T) {
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValueTotalPages *int
		obj.SetTotalPages(fernTestValueTotalPages)
		assert.Equal(t, fernTestValueTotalPages, obj.TotalPages)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHasNext", func(t *testing.T) {
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValueHasNext *bool
		obj.SetHasNext(fernTestValueHasNext)
		assert.Equal(t, fernTestValueHasNext, obj.HasNext)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHasPrevious", func(t *testing.T) {
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValueHasPrevious *bool
		obj.SetHasPrevious(fernTestValueHasPrevious)
		assert.Equal(t, fernTestValueHasPrevious, obj.HasPrevious)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersPaginatedResponseDocumentResponse(t *testing.T) {
	t.Run("GetItems", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var expected []*DocumentResponse
		obj.Items = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetItems(), "getter should return the property value")
	})

	t.Run("GetItems_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		obj.Items = nil

		// Act & Assert
		assert.Nil(t, obj.GetItems(), "getter should return nil when property is nil")
	})

	t.Run("GetItems_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseDocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetItems() // Should return zero value
	})

	t.Run("GetPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var expected *int
		obj.Page = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPage(), "getter should return the property value")
	})

	t.Run("GetPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		obj.Page = nil

		// Act & Assert
		assert.Nil(t, obj.GetPage(), "getter should return nil when property is nil")
	})

	t.Run("GetPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseDocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPage() // Should return zero value
	})

	t.Run("GetPageSize", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var expected *int
		obj.PageSize = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPageSize(), "getter should return the property value")
	})

	t.Run("GetPageSize_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		obj.PageSize = nil

		// Act & Assert
		assert.Nil(t, obj.GetPageSize(), "getter should return nil when property is nil")
	})

	t.Run("GetPageSize_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseDocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPageSize() // Should return zero value
	})

	t.Run("GetItemsInPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var expected *int
		obj.ItemsInPage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetItemsInPage(), "getter should return the property value")
	})

	t.Run("GetItemsInPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		obj.ItemsInPage = nil

		// Act & Assert
		assert.Nil(t, obj.GetItemsInPage(), "getter should return nil when property is nil")
	})

	t.Run("GetItemsInPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseDocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetItemsInPage() // Should return zero value
	})

	t.Run("GetTotalItems", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var expected *int
		obj.TotalItems = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTotalItems(), "getter should return the property value")
	})

	t.Run("GetTotalItems_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		obj.TotalItems = nil

		// Act & Assert
		assert.Nil(t, obj.GetTotalItems(), "getter should return nil when property is nil")
	})

	t.Run("GetTotalItems_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseDocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTotalItems() // Should return zero value
	})

	t.Run("GetTotalPages", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var expected *int
		obj.TotalPages = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTotalPages(), "getter should return the property value")
	})

	t.Run("GetTotalPages_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		obj.TotalPages = nil

		// Act & Assert
		assert.Nil(t, obj.GetTotalPages(), "getter should return nil when property is nil")
	})

	t.Run("GetTotalPages_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseDocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTotalPages() // Should return zero value
	})

	t.Run("GetHasNext", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var expected *bool
		obj.HasNext = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHasNext(), "getter should return the property value")
	})

	t.Run("GetHasNext_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		obj.HasNext = nil

		// Act & Assert
		assert.Nil(t, obj.GetHasNext(), "getter should return nil when property is nil")
	})

	t.Run("GetHasNext_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseDocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHasNext() // Should return zero value
	})

	t.Run("GetHasPrevious", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var expected *bool
		obj.HasPrevious = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHasPrevious(), "getter should return the property value")
	})

	t.Run("GetHasPrevious_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		obj.HasPrevious = nil

		// Act & Assert
		assert.Nil(t, obj.GetHasPrevious(), "getter should return nil when property is nil")
	})

	t.Run("GetHasPrevious_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseDocumentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHasPrevious() // Should return zero value
	})

}

func TestSettersMarkExplicitPaginatedResponseDocumentResponse(t *testing.T) {
	t.Run("SetItems_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValueItems []*DocumentResponse

		// Act
		obj.SetItems(fernTestValueItems)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPageSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValuePageSize *int

		// Act
		obj.SetPageSize(fernTestValuePageSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetItemsInPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValueItemsInPage *int

		// Act
		obj.SetItemsInPage(fernTestValueItemsInPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTotalItems_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValueTotalItems *int

		// Act
		obj.SetTotalItems(fernTestValueTotalItems)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTotalPages_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValueTotalPages *int

		// Act
		obj.SetTotalPages(fernTestValueTotalPages)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHasNext_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValueHasNext *bool

		// Act
		obj.SetHasNext(fernTestValueHasNext)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHasPrevious_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}
		var fernTestValueHasPrevious *bool

		// Act
		obj.SetHasPrevious(fernTestValueHasPrevious)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDocumentCreatePayload(t *testing.T) {
	t.Run("SetClientID", func(t *testing.T) {
		obj := &DocumentCreatePayload{}
		var fernTestValueClientID *string
		obj.SetClientID(fernTestValueClientID)
		assert.Equal(t, fernTestValueClientID, obj.ClientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLoanID", func(t *testing.T) {
		obj := &DocumentCreatePayload{}
		var fernTestValueLoanID *string
		obj.SetLoanID(fernTestValueLoanID)
		assert.Equal(t, fernTestValueLoanID, obj.LoanID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetInstallmentID", func(t *testing.T) {
		obj := &DocumentCreatePayload{}
		var fernTestValueInstallmentID *string
		obj.SetInstallmentID(fernTestValueInstallmentID)
		assert.Equal(t, fernTestValueInstallmentID, obj.InstallmentID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWaterfallID", func(t *testing.T) {
		obj := &DocumentCreatePayload{}
		var fernTestValueWaterfallID *string
		obj.SetWaterfallID(fernTestValueWaterfallID)
		assert.Equal(t, fernTestValueWaterfallID, obj.WaterfallID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDocumentCreatePayload(t *testing.T) {
	t.Run("SetClientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentCreatePayload{}
		var fernTestValueClientID *string

		// Act
		obj.SetClientID(fernTestValueClientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLoanID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentCreatePayload{}
		var fernTestValueLoanID *string

		// Act
		obj.SetLoanID(fernTestValueLoanID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetInstallmentID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentCreatePayload{}
		var fernTestValueInstallmentID *string

		// Act
		obj.SetInstallmentID(fernTestValueInstallmentID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWaterfallID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentCreatePayload{}
		var fernTestValueWaterfallID *string

		// Act
		obj.SetWaterfallID(fernTestValueWaterfallID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingAvailableDocumentCategoriesResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AvailableDocumentCategoriesResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled AvailableDocumentCategoriesResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj AvailableDocumentCategoriesResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj AvailableDocumentCategoriesResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingDocumentResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DocumentResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled DocumentResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj DocumentResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj DocumentResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingPaginatedResponseDocumentResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseDocumentResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled PaginatedResponseDocumentResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj PaginatedResponseDocumentResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj PaginatedResponseDocumentResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringAvailableDocumentCategoriesResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &AvailableDocumentCategoriesResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AvailableDocumentCategoriesResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringDocumentResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &DocumentResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringPaginatedResponseDocumentResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &PaginatedResponseDocumentResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseDocumentResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesAvailableDocumentCategoriesResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &AvailableDocumentCategoriesResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AvailableDocumentCategoriesResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesDocumentResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &DocumentResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DocumentResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesPaginatedResponseDocumentResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &PaginatedResponseDocumentResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseDocumentResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
