// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	big "math/big"
	time "time"
)

var (
	installmentCreatePayloadFieldLoanID       = big.NewInt(1 << 0)
	installmentCreatePayloadFieldInstallments = big.NewInt(1 << 1)
)

type InstallmentCreatePayload struct {
	// The loan ID to add the installments to
	LoanID string `json:"loan_id" url:"-"`
	// List of installments to add to the loan
	Installments []*LoanInstallmentCreatePayload `json:"installments" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InstallmentCreatePayload) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetLoanID sets the LoanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallmentCreatePayload) SetLoanID(loanID string) {
	i.LoanID = loanID
	i.require(installmentCreatePayloadFieldLoanID)
}

// SetInstallments sets the Installments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallmentCreatePayload) SetInstallments(installments []*LoanInstallmentCreatePayload) {
	i.Installments = installments
	i.require(installmentCreatePayloadFieldInstallments)
}

func (i *InstallmentCreatePayload) UnmarshalJSON(data []byte) error {
	type unmarshaler InstallmentCreatePayload
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*i = InstallmentCreatePayload(body)
	return nil
}

func (i *InstallmentCreatePayload) MarshalJSON() ([]byte, error) {
	type embed InstallmentCreatePayload
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	paymentPromiseCreatePayloadFieldInstallmentID = big.NewInt(1 << 0)
	paymentPromiseCreatePayloadFieldAmount        = big.NewInt(1 << 1)
	paymentPromiseCreatePayloadFieldPromisedDate  = big.NewInt(1 << 2)
	paymentPromiseCreatePayloadFieldNotes         = big.NewInt(1 << 3)
)

type PaymentPromiseCreatePayload struct {
	// The ID of the installment this promise relates to
	InstallmentID string `json:"installment_id" url:"-"`
	// The amount the client has promised to pay (must be > 0)
	Amount *PaymentPromiseCreatePayloadAmount `json:"amount" url:"-"`
	// The date the client has committed to pay by (today or future)
	PromisedDate time.Time `json:"promised_date" url:"-" format:"date"`
	// Optional notes captured during the collections interaction
	Notes *string `json:"notes,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PaymentPromiseCreatePayload) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetInstallmentID sets the InstallmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseCreatePayload) SetInstallmentID(installmentID string) {
	p.InstallmentID = installmentID
	p.require(paymentPromiseCreatePayloadFieldInstallmentID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseCreatePayload) SetAmount(amount *PaymentPromiseCreatePayloadAmount) {
	p.Amount = amount
	p.require(paymentPromiseCreatePayloadFieldAmount)
}

// SetPromisedDate sets the PromisedDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseCreatePayload) SetPromisedDate(promisedDate time.Time) {
	p.PromisedDate = promisedDate
	p.require(paymentPromiseCreatePayloadFieldPromisedDate)
}

// SetNotes sets the Notes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseCreatePayload) SetNotes(notes *string) {
	p.Notes = notes
	p.require(paymentPromiseCreatePayloadFieldNotes)
}

func (p *PaymentPromiseCreatePayload) UnmarshalJSON(data []byte) error {
	type unmarshaler PaymentPromiseCreatePayload
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PaymentPromiseCreatePayload(body)
	return nil
}

func (p *PaymentPromiseCreatePayload) MarshalJSON() ([]byte, error) {
	type embed PaymentPromiseCreatePayload
	var marshaler = struct {
		embed
		PromisedDate *internal.Date `json:"promised_date"`
	}{
		embed:        embed(*p),
		PromisedDate: internal.NewDate(p.PromisedDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteInstallmentRequestFieldInstallmentID = big.NewInt(1 << 0)
)

type DeleteInstallmentRequest struct {
	InstallmentID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteInstallmentRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetInstallmentID sets the InstallmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteInstallmentRequest) SetInstallmentID(installmentID string) {
	d.InstallmentID = installmentID
	d.require(deleteInstallmentRequestFieldInstallmentID)
}

var (
	installmentEditPayloadFieldInstallmentID       = big.NewInt(1 << 0)
	installmentEditPayloadFieldAmount              = big.NewInt(1 << 1)
	installmentEditPayloadFieldExpectedRepaymentAt = big.NewInt(1 << 2)
)

type InstallmentEditPayload struct {
	InstallmentID string `json:"-" url:"-"`
	// The new amount for the installment
	Amount *InstallmentEditPayloadAmount `json:"amount" url:"-"`
	// The new expected repayment date
	ExpectedRepaymentAt time.Time `json:"expected_repayment_at" url:"-" format:"date"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InstallmentEditPayload) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetInstallmentID sets the InstallmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallmentEditPayload) SetInstallmentID(installmentID string) {
	i.InstallmentID = installmentID
	i.require(installmentEditPayloadFieldInstallmentID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallmentEditPayload) SetAmount(amount *InstallmentEditPayloadAmount) {
	i.Amount = amount
	i.require(installmentEditPayloadFieldAmount)
}

// SetExpectedRepaymentAt sets the ExpectedRepaymentAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallmentEditPayload) SetExpectedRepaymentAt(expectedRepaymentAt time.Time) {
	i.ExpectedRepaymentAt = expectedRepaymentAt
	i.require(installmentEditPayloadFieldExpectedRepaymentAt)
}

func (i *InstallmentEditPayload) UnmarshalJSON(data []byte) error {
	type unmarshaler InstallmentEditPayload
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*i = InstallmentEditPayload(body)
	return nil
}

func (i *InstallmentEditPayload) MarshalJSON() ([]byte, error) {
	type embed InstallmentEditPayload
	var marshaler = struct {
		embed
		ExpectedRepaymentAt *internal.Date `json:"expected_repayment_at"`
	}{
		embed:               embed(*i),
		ExpectedRepaymentAt: internal.NewDate(i.ExpectedRepaymentAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getInstallmentByIDRequestFieldInstallmentID = big.NewInt(1 << 0)
)

type GetInstallmentByIDRequest struct {
	InstallmentID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetInstallmentByIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetInstallmentID sets the InstallmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetInstallmentByIDRequest) SetInstallmentID(installmentID string) {
	g.InstallmentID = installmentID
	g.require(getInstallmentByIDRequestFieldInstallmentID)
}

var (
	listInstallmentsRequestFieldPage     = big.NewInt(1 << 0)
	listInstallmentsRequestFieldPageSize = big.NewInt(1 << 1)
	listInstallmentsRequestFieldClientID = big.NewInt(1 << 2)
	listInstallmentsRequestFieldLoanID   = big.NewInt(1 << 3)
	listInstallmentsRequestFieldOrderBy  = big.NewInt(1 << 4)
	listInstallmentsRequestFieldQ        = big.NewInt(1 << 5)
)

type ListInstallmentsRequest struct {
	Page     *int    `json:"-" url:"page,omitempty"`
	PageSize *int    `json:"-" url:"page_size,omitempty"`
	ClientID *string `json:"-" url:"client_id,omitempty"`
	LoanID   *string `json:"-" url:"loan_id,omitempty"`
	// Field to order the results by, e.g., 'created_at:desc,updated_at:asc'
	OrderBy *string `json:"-" url:"order_by,omitempty"`
	// Query string for filtering. Format: "field:operator:value;...". Supported fields: id, client_id, loan_id, status, client.name, expected_repayment_at. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.
	Q *string `json:"-" url:"q,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListInstallmentsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInstallmentsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listInstallmentsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInstallmentsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listInstallmentsRequestFieldPageSize)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInstallmentsRequest) SetClientID(clientID *string) {
	l.ClientID = clientID
	l.require(listInstallmentsRequestFieldClientID)
}

// SetLoanID sets the LoanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInstallmentsRequest) SetLoanID(loanID *string) {
	l.LoanID = loanID
	l.require(listInstallmentsRequestFieldLoanID)
}

// SetOrderBy sets the OrderBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInstallmentsRequest) SetOrderBy(orderBy *string) {
	l.OrderBy = orderBy
	l.require(listInstallmentsRequestFieldOrderBy)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInstallmentsRequest) SetQ(q *string) {
	l.Q = q
	l.require(listInstallmentsRequestFieldQ)
}

var (
	listPaymentPromisesRequestFieldPage     = big.NewInt(1 << 0)
	listPaymentPromisesRequestFieldPageSize = big.NewInt(1 << 1)
	listPaymentPromisesRequestFieldOrderBy  = big.NewInt(1 << 2)
	listPaymentPromisesRequestFieldQ        = big.NewInt(1 << 3)
	listPaymentPromisesRequestFieldLoanID   = big.NewInt(1 << 4)
	listPaymentPromisesRequestFieldClientID = big.NewInt(1 << 5)
)

type ListPaymentPromisesRequest struct {
	Page     *int `json:"-" url:"page,omitempty"`
	PageSize *int `json:"-" url:"page_size,omitempty"`
	// Field to order the results by, e.g., 'created_at:desc,updated_at:asc'
	OrderBy *string `json:"-" url:"order_by,omitempty"`
	// Query string for filtering. Format: "field:operator:value;...". Supported fields: id, installment_id, status, promised_date, created_at. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.
	Q        *string `json:"-" url:"q,omitempty"`
	LoanID   *string `json:"-" url:"loan_id,omitempty"`
	ClientID *string `json:"-" url:"client_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListPaymentPromisesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPaymentPromisesRequest) SetPage(page *int) {
	l.Page = page
	l.require(listPaymentPromisesRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPaymentPromisesRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listPaymentPromisesRequestFieldPageSize)
}

// SetOrderBy sets the OrderBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPaymentPromisesRequest) SetOrderBy(orderBy *string) {
	l.OrderBy = orderBy
	l.require(listPaymentPromisesRequestFieldOrderBy)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPaymentPromisesRequest) SetQ(q *string) {
	l.Q = q
	l.require(listPaymentPromisesRequestFieldQ)
}

// SetLoanID sets the LoanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPaymentPromisesRequest) SetLoanID(loanID *string) {
	l.LoanID = loanID
	l.require(listPaymentPromisesRequestFieldLoanID)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPaymentPromisesRequest) SetClientID(clientID *string) {
	l.ClientID = clientID
	l.require(listPaymentPromisesRequestFieldClientID)
}

var (
	paginatedResponsePaymentPromiseResponseFieldItems       = big.NewInt(1 << 0)
	paginatedResponsePaymentPromiseResponseFieldPage        = big.NewInt(1 << 1)
	paginatedResponsePaymentPromiseResponseFieldPageSize    = big.NewInt(1 << 2)
	paginatedResponsePaymentPromiseResponseFieldItemsInPage = big.NewInt(1 << 3)
	paginatedResponsePaymentPromiseResponseFieldTotalItems  = big.NewInt(1 << 4)
	paginatedResponsePaymentPromiseResponseFieldTotalPages  = big.NewInt(1 << 5)
	paginatedResponsePaymentPromiseResponseFieldHasNext     = big.NewInt(1 << 6)
	paginatedResponsePaymentPromiseResponseFieldHasPrevious = big.NewInt(1 << 7)
)

type PaginatedResponsePaymentPromiseResponse struct {
	Items []*PaymentPromiseResponse `json:"items" url:"items"`
	// Current page number
	Page *int `json:"page,omitempty" url:"page,omitempty"`
	// Number of items per page
	PageSize *int `json:"page_size,omitempty" url:"page_size,omitempty"`
	// Number of items in the current page
	ItemsInPage *int `json:"items_in_page,omitempty" url:"items_in_page,omitempty"`
	// Total number of items across all pages
	TotalItems *int `json:"total_items,omitempty" url:"total_items,omitempty"`
	// Total number of pages available
	TotalPages *int `json:"total_pages,omitempty" url:"total_pages,omitempty"`
	// Indicates if there is a next page
	HasNext *bool `json:"has_next,omitempty" url:"has_next,omitempty"`
	// Indicates if there is a previous page
	HasPrevious *bool `json:"has_previous,omitempty" url:"has_previous,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginatedResponsePaymentPromiseResponse) GetItems() []*PaymentPromiseResponse {
	if p == nil {
		return nil
	}
	return p.Items
}

func (p *PaginatedResponsePaymentPromiseResponse) GetPage() *int {
	if p == nil {
		return nil
	}
	return p.Page
}

func (p *PaginatedResponsePaymentPromiseResponse) GetPageSize() *int {
	if p == nil {
		return nil
	}
	return p.PageSize
}

func (p *PaginatedResponsePaymentPromiseResponse) GetItemsInPage() *int {
	if p == nil {
		return nil
	}
	return p.ItemsInPage
}

func (p *PaginatedResponsePaymentPromiseResponse) GetTotalItems() *int {
	if p == nil {
		return nil
	}
	return p.TotalItems
}

func (p *PaginatedResponsePaymentPromiseResponse) GetTotalPages() *int {
	if p == nil {
		return nil
	}
	return p.TotalPages
}

func (p *PaginatedResponsePaymentPromiseResponse) GetHasNext() *bool {
	if p == nil {
		return nil
	}
	return p.HasNext
}

func (p *PaginatedResponsePaymentPromiseResponse) GetHasPrevious() *bool {
	if p == nil {
		return nil
	}
	return p.HasPrevious
}

func (p *PaginatedResponsePaymentPromiseResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PaginatedResponsePaymentPromiseResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponsePaymentPromiseResponse) SetItems(items []*PaymentPromiseResponse) {
	p.Items = items
	p.require(paginatedResponsePaymentPromiseResponseFieldItems)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponsePaymentPromiseResponse) SetPage(page *int) {
	p.Page = page
	p.require(paginatedResponsePaymentPromiseResponseFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponsePaymentPromiseResponse) SetPageSize(pageSize *int) {
	p.PageSize = pageSize
	p.require(paginatedResponsePaymentPromiseResponseFieldPageSize)
}

// SetItemsInPage sets the ItemsInPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponsePaymentPromiseResponse) SetItemsInPage(itemsInPage *int) {
	p.ItemsInPage = itemsInPage
	p.require(paginatedResponsePaymentPromiseResponseFieldItemsInPage)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponsePaymentPromiseResponse) SetTotalItems(totalItems *int) {
	p.TotalItems = totalItems
	p.require(paginatedResponsePaymentPromiseResponseFieldTotalItems)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponsePaymentPromiseResponse) SetTotalPages(totalPages *int) {
	p.TotalPages = totalPages
	p.require(paginatedResponsePaymentPromiseResponseFieldTotalPages)
}

// SetHasNext sets the HasNext field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponsePaymentPromiseResponse) SetHasNext(hasNext *bool) {
	p.HasNext = hasNext
	p.require(paginatedResponsePaymentPromiseResponseFieldHasNext)
}

// SetHasPrevious sets the HasPrevious field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponsePaymentPromiseResponse) SetHasPrevious(hasPrevious *bool) {
	p.HasPrevious = hasPrevious
	p.require(paginatedResponsePaymentPromiseResponseFieldHasPrevious)
}

func (p *PaginatedResponsePaymentPromiseResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedResponsePaymentPromiseResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedResponsePaymentPromiseResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedResponsePaymentPromiseResponse) MarshalJSON() ([]byte, error) {
	type embed PaginatedResponsePaymentPromiseResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginatedResponsePaymentPromiseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	paymentPromiseResponseFieldID            = big.NewInt(1 << 0)
	paymentPromiseResponseFieldCreatedAt     = big.NewInt(1 << 1)
	paymentPromiseResponseFieldUpdatedAt     = big.NewInt(1 << 2)
	paymentPromiseResponseFieldInstallmentID = big.NewInt(1 << 3)
	paymentPromiseResponseFieldPartnerID     = big.NewInt(1 << 4)
	paymentPromiseResponseFieldClientID      = big.NewInt(1 << 5)
	paymentPromiseResponseFieldLoanID        = big.NewInt(1 << 6)
	paymentPromiseResponseFieldAmount        = big.NewInt(1 << 7)
	paymentPromiseResponseFieldPromisedDate  = big.NewInt(1 << 8)
	paymentPromiseResponseFieldStatus        = big.NewInt(1 << 9)
	paymentPromiseResponseFieldNotes         = big.NewInt(1 << 10)
)

type PaymentPromiseResponse struct {
	// The ID of the payment promise
	ID string `json:"id" url:"id"`
	// When the promise was created
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// When the promise was last updated
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`
	// The ID of the installment this promise relates to
	InstallmentID string `json:"installment_id" url:"installment_id"`
	// The ID of the partner the installment belongs to
	PartnerID string `json:"partner_id" url:"partner_id"`
	// The ID of the client the installment belongs to
	ClientID string `json:"client_id" url:"client_id"`
	// The ID of the loan the installment belongs to
	LoanID string `json:"loan_id" url:"loan_id"`
	// The amount the client has promised to pay
	Amount string `json:"amount" url:"amount"`
	// The date the client has committed to pay by
	PromisedDate time.Time `json:"promised_date" url:"promised_date" format:"date"`
	// The status of the promise
	Status PaymentPromiseStatusEnum `json:"status" url:"status"`
	// Optional notes captured during the collections interaction
	Notes *string `json:"notes,omitempty" url:"notes,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaymentPromiseResponse) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PaymentPromiseResponse) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PaymentPromiseResponse) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *PaymentPromiseResponse) GetInstallmentID() string {
	if p == nil {
		return ""
	}
	return p.InstallmentID
}

func (p *PaymentPromiseResponse) GetPartnerID() string {
	if p == nil {
		return ""
	}
	return p.PartnerID
}

func (p *PaymentPromiseResponse) GetClientID() string {
	if p == nil {
		return ""
	}
	return p.ClientID
}

func (p *PaymentPromiseResponse) GetLoanID() string {
	if p == nil {
		return ""
	}
	return p.LoanID
}

func (p *PaymentPromiseResponse) GetAmount() string {
	if p == nil {
		return ""
	}
	return p.Amount
}

func (p *PaymentPromiseResponse) GetPromisedDate() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.PromisedDate
}

func (p *PaymentPromiseResponse) GetStatus() PaymentPromiseStatusEnum {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *PaymentPromiseResponse) GetNotes() *string {
	if p == nil {
		return nil
	}
	return p.Notes
}

func (p *PaymentPromiseResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PaymentPromiseResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseResponse) SetID(id string) {
	p.ID = id
	p.require(paymentPromiseResponseFieldID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseResponse) SetCreatedAt(createdAt time.Time) {
	p.CreatedAt = createdAt
	p.require(paymentPromiseResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseResponse) SetUpdatedAt(updatedAt time.Time) {
	p.UpdatedAt = updatedAt
	p.require(paymentPromiseResponseFieldUpdatedAt)
}

// SetInstallmentID sets the InstallmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseResponse) SetInstallmentID(installmentID string) {
	p.InstallmentID = installmentID
	p.require(paymentPromiseResponseFieldInstallmentID)
}

// SetPartnerID sets the PartnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseResponse) SetPartnerID(partnerID string) {
	p.PartnerID = partnerID
	p.require(paymentPromiseResponseFieldPartnerID)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseResponse) SetClientID(clientID string) {
	p.ClientID = clientID
	p.require(paymentPromiseResponseFieldClientID)
}

// SetLoanID sets the LoanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseResponse) SetLoanID(loanID string) {
	p.LoanID = loanID
	p.require(paymentPromiseResponseFieldLoanID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseResponse) SetAmount(amount string) {
	p.Amount = amount
	p.require(paymentPromiseResponseFieldAmount)
}

// SetPromisedDate sets the PromisedDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseResponse) SetPromisedDate(promisedDate time.Time) {
	p.PromisedDate = promisedDate
	p.require(paymentPromiseResponseFieldPromisedDate)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseResponse) SetStatus(status PaymentPromiseStatusEnum) {
	p.Status = status
	p.require(paymentPromiseResponseFieldStatus)
}

// SetNotes sets the Notes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaymentPromiseResponse) SetNotes(notes *string) {
	p.Notes = notes
	p.require(paymentPromiseResponseFieldNotes)
}

func (p *PaymentPromiseResponse) UnmarshalJSON(data []byte) error {
	type embed PaymentPromiseResponse
	var unmarshaler = struct {
		embed
		CreatedAt    *internal.DateTime `json:"created_at"`
		UpdatedAt    *internal.DateTime `json:"updated_at"`
		PromisedDate *internal.Date     `json:"promised_date"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PaymentPromiseResponse(unmarshaler.embed)
	p.CreatedAt = unmarshaler.CreatedAt.Time()
	p.UpdatedAt = unmarshaler.UpdatedAt.Time()
	p.PromisedDate = unmarshaler.PromisedDate.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentPromiseResponse) MarshalJSON() ([]byte, error) {
	type embed PaymentPromiseResponse
	var marshaler = struct {
		embed
		CreatedAt    *internal.DateTime `json:"created_at"`
		UpdatedAt    *internal.DateTime `json:"updated_at"`
		PromisedDate *internal.Date     `json:"promised_date"`
	}{
		embed:        embed(*p),
		CreatedAt:    internal.NewDateTime(p.CreatedAt),
		UpdatedAt:    internal.NewDateTime(p.UpdatedAt),
		PromisedDate: internal.NewDate(p.PromisedDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaymentPromiseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PaymentPromiseStatusEnum string

const (
	PaymentPromiseStatusEnumActive    PaymentPromiseStatusEnum = "active"
	PaymentPromiseStatusEnumPaid      PaymentPromiseStatusEnum = "paid"
	PaymentPromiseStatusEnumNotPaid   PaymentPromiseStatusEnum = "not_paid"
	PaymentPromiseStatusEnumCancelled PaymentPromiseStatusEnum = "cancelled"
)

func NewPaymentPromiseStatusEnumFromString(s string) (PaymentPromiseStatusEnum, error) {
	switch s {
	case "active":
		return PaymentPromiseStatusEnumActive, nil
	case "paid":
		return PaymentPromiseStatusEnumPaid, nil
	case "not_paid":
		return PaymentPromiseStatusEnumNotPaid, nil
	case "cancelled":
		return PaymentPromiseStatusEnumCancelled, nil
	}
	var t PaymentPromiseStatusEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PaymentPromiseStatusEnum) Ptr() *PaymentPromiseStatusEnum {
	return &p
}

// The new amount for the installment
type InstallmentEditPayloadAmount struct {
	Double float64
	String string

	typ string
}

func (i *InstallmentEditPayloadAmount) GetDouble() float64 {
	if i == nil {
		return 0
	}
	return i.Double
}

func (i *InstallmentEditPayloadAmount) GetString() string {
	if i == nil {
		return ""
	}
	return i.String
}

func (i *InstallmentEditPayloadAmount) UnmarshalJSON(data []byte) error {
	var valueDouble float64
	if err := json.Unmarshal(data, &valueDouble); err == nil {
		i.typ = "Double"
		i.Double = valueDouble
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		i.typ = "String"
		i.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, i)
}

func (i InstallmentEditPayloadAmount) MarshalJSON() ([]byte, error) {
	if i.typ == "Double" || i.Double != 0 {
		return json.Marshal(i.Double)
	}
	if i.typ == "String" || i.String != "" {
		return json.Marshal(i.String)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", i)
}

type InstallmentEditPayloadAmountVisitor interface {
	VisitDouble(float64) error
	VisitString(string) error
}

func (i *InstallmentEditPayloadAmount) Accept(visitor InstallmentEditPayloadAmountVisitor) error {
	if i.typ == "Double" || i.Double != 0 {
		return visitor.VisitDouble(i.Double)
	}
	if i.typ == "String" || i.String != "" {
		return visitor.VisitString(i.String)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", i)
}

// The amount the client has promised to pay (must be > 0)
type PaymentPromiseCreatePayloadAmount struct {
	Double float64
	String string

	typ string
}

func (p *PaymentPromiseCreatePayloadAmount) GetDouble() float64 {
	if p == nil {
		return 0
	}
	return p.Double
}

func (p *PaymentPromiseCreatePayloadAmount) GetString() string {
	if p == nil {
		return ""
	}
	return p.String
}

func (p *PaymentPromiseCreatePayloadAmount) UnmarshalJSON(data []byte) error {
	var valueDouble float64
	if err := json.Unmarshal(data, &valueDouble); err == nil {
		p.typ = "Double"
		p.Double = valueDouble
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		p.typ = "String"
		p.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, p)
}

func (p PaymentPromiseCreatePayloadAmount) MarshalJSON() ([]byte, error) {
	if p.typ == "Double" || p.Double != 0 {
		return json.Marshal(p.Double)
	}
	if p.typ == "String" || p.String != "" {
		return json.Marshal(p.String)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", p)
}

type PaymentPromiseCreatePayloadAmountVisitor interface {
	VisitDouble(float64) error
	VisitString(string) error
}

func (p *PaymentPromiseCreatePayloadAmount) Accept(visitor PaymentPromiseCreatePayloadAmountVisitor) error {
	if p.typ == "Double" || p.Double != 0 {
		return visitor.VisitDouble(p.Double)
	}
	if p.typ == "String" || p.String != "" {
		return visitor.VisitString(p.String)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", p)
}
