// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	big "math/big"
	time "time"
)

var (
	investorGetClientRequestFieldClientID = big.NewInt(1 << 0)
)

type InvestorGetClientRequest struct {
	ClientID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InvestorGetClientRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorGetClientRequest) SetClientID(clientID string) {
	i.ClientID = clientID
	i.require(investorGetClientRequestFieldClientID)
}

var (
	investorGetInstallmentRequestFieldInstallmentID = big.NewInt(1 << 0)
)

type InvestorGetInstallmentRequest struct {
	InstallmentID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InvestorGetInstallmentRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetInstallmentID sets the InstallmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorGetInstallmentRequest) SetInstallmentID(installmentID string) {
	i.InstallmentID = installmentID
	i.require(investorGetInstallmentRequestFieldInstallmentID)
}

var (
	investorGetLoanRequestFieldLoanID = big.NewInt(1 << 0)
)

type InvestorGetLoanRequest struct {
	LoanID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InvestorGetLoanRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetLoanID sets the LoanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorGetLoanRequest) SetLoanID(loanID string) {
	i.LoanID = loanID
	i.require(investorGetLoanRequestFieldLoanID)
}

var (
	investorListClientsRequestFieldPage     = big.NewInt(1 << 0)
	investorListClientsRequestFieldPageSize = big.NewInt(1 << 1)
	investorListClientsRequestFieldOrderBy  = big.NewInt(1 << 2)
	investorListClientsRequestFieldQ        = big.NewInt(1 << 3)
)

type InvestorListClientsRequest struct {
	Page     *int    `json:"-" url:"page,omitempty"`
	PageSize *int    `json:"-" url:"page_size,omitempty"`
	OrderBy  *string `json:"-" url:"order_by,omitempty"`
	// Query string for filtering. Format: "field:operator:value;...". Supported fields: id, name, correlation_id, company_number, status. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.
	Q *string `json:"-" url:"q,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InvestorListClientsRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListClientsRequest) SetPage(page *int) {
	i.Page = page
	i.require(investorListClientsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListClientsRequest) SetPageSize(pageSize *int) {
	i.PageSize = pageSize
	i.require(investorListClientsRequestFieldPageSize)
}

// SetOrderBy sets the OrderBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListClientsRequest) SetOrderBy(orderBy *string) {
	i.OrderBy = orderBy
	i.require(investorListClientsRequestFieldOrderBy)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListClientsRequest) SetQ(q *string) {
	i.Q = q
	i.require(investorListClientsRequestFieldQ)
}

var (
	investorListInstallmentsRequestFieldPage     = big.NewInt(1 << 0)
	investorListInstallmentsRequestFieldPageSize = big.NewInt(1 << 1)
	investorListInstallmentsRequestFieldClientID = big.NewInt(1 << 2)
	investorListInstallmentsRequestFieldLoanID   = big.NewInt(1 << 3)
	investorListInstallmentsRequestFieldOrderBy  = big.NewInt(1 << 4)
	investorListInstallmentsRequestFieldQ        = big.NewInt(1 << 5)
)

type InvestorListInstallmentsRequest struct {
	Page     *int    `json:"-" url:"page,omitempty"`
	PageSize *int    `json:"-" url:"page_size,omitempty"`
	ClientID *string `json:"-" url:"client_id,omitempty"`
	LoanID   *string `json:"-" url:"loan_id,omitempty"`
	OrderBy  *string `json:"-" url:"order_by,omitempty"`
	// Query string for filtering. Format: "field:operator:value;...". Supported fields: id, client_id, loan_id, status, client.name, expected_repayment_at. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.
	Q *string `json:"-" url:"q,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InvestorListInstallmentsRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListInstallmentsRequest) SetPage(page *int) {
	i.Page = page
	i.require(investorListInstallmentsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListInstallmentsRequest) SetPageSize(pageSize *int) {
	i.PageSize = pageSize
	i.require(investorListInstallmentsRequestFieldPageSize)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListInstallmentsRequest) SetClientID(clientID *string) {
	i.ClientID = clientID
	i.require(investorListInstallmentsRequestFieldClientID)
}

// SetLoanID sets the LoanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListInstallmentsRequest) SetLoanID(loanID *string) {
	i.LoanID = loanID
	i.require(investorListInstallmentsRequestFieldLoanID)
}

// SetOrderBy sets the OrderBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListInstallmentsRequest) SetOrderBy(orderBy *string) {
	i.OrderBy = orderBy
	i.require(investorListInstallmentsRequestFieldOrderBy)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListInstallmentsRequest) SetQ(q *string) {
	i.Q = q
	i.require(investorListInstallmentsRequestFieldQ)
}

var (
	investorListLoansRequestFieldPage     = big.NewInt(1 << 0)
	investorListLoansRequestFieldPageSize = big.NewInt(1 << 1)
	investorListLoansRequestFieldClientID = big.NewInt(1 << 2)
	investorListLoansRequestFieldOrderBy  = big.NewInt(1 << 3)
	investorListLoansRequestFieldQ        = big.NewInt(1 << 4)
)

type InvestorListLoansRequest struct {
	Page     *int    `json:"-" url:"page,omitempty"`
	PageSize *int    `json:"-" url:"page_size,omitempty"`
	ClientID *string `json:"-" url:"client_id,omitempty"`
	OrderBy  *string `json:"-" url:"order_by,omitempty"`
	// Query string for filtering. Format: "field:operator:value;...". Supported fields: id, partner_id, client_id, status, loan_date, currency, partner.name, client.name. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.
	Q *string `json:"-" url:"q,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InvestorListLoansRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListLoansRequest) SetPage(page *int) {
	i.Page = page
	i.require(investorListLoansRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListLoansRequest) SetPageSize(pageSize *int) {
	i.PageSize = pageSize
	i.require(investorListLoansRequestFieldPageSize)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListLoansRequest) SetClientID(clientID *string) {
	i.ClientID = clientID
	i.require(investorListLoansRequestFieldClientID)
}

// SetOrderBy sets the OrderBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListLoansRequest) SetOrderBy(orderBy *string) {
	i.OrderBy = orderBy
	i.require(investorListLoansRequestFieldOrderBy)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListLoansRequest) SetQ(q *string) {
	i.Q = q
	i.require(investorListLoansRequestFieldQ)
}

var (
	investorListRepaymentsRequestFieldClientID      = big.NewInt(1 << 0)
	investorListRepaymentsRequestFieldLoanID        = big.NewInt(1 << 1)
	investorListRepaymentsRequestFieldInstallmentID = big.NewInt(1 << 2)
	investorListRepaymentsRequestFieldPage          = big.NewInt(1 << 3)
	investorListRepaymentsRequestFieldPageSize      = big.NewInt(1 << 4)
	investorListRepaymentsRequestFieldOrderBy       = big.NewInt(1 << 5)
	investorListRepaymentsRequestFieldQ             = big.NewInt(1 << 6)
)

type InvestorListRepaymentsRequest struct {
	ClientID      *string `json:"-" url:"client_id,omitempty"`
	LoanID        *string `json:"-" url:"loan_id,omitempty"`
	InstallmentID *string `json:"-" url:"installment_id,omitempty"`
	Page          *int    `json:"-" url:"page,omitempty"`
	PageSize      *int    `json:"-" url:"page_size,omitempty"`
	OrderBy       *string `json:"-" url:"order_by,omitempty"`
	// Query string for filtering. Format: "field:operator:value;...". Supported fields: id, client_id, loan_id, installment_id, created_at, client.name, client.correlation_id. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.
	Q *string `json:"-" url:"q,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InvestorListRepaymentsRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListRepaymentsRequest) SetClientID(clientID *string) {
	i.ClientID = clientID
	i.require(investorListRepaymentsRequestFieldClientID)
}

// SetLoanID sets the LoanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListRepaymentsRequest) SetLoanID(loanID *string) {
	i.LoanID = loanID
	i.require(investorListRepaymentsRequestFieldLoanID)
}

// SetInstallmentID sets the InstallmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListRepaymentsRequest) SetInstallmentID(installmentID *string) {
	i.InstallmentID = installmentID
	i.require(investorListRepaymentsRequestFieldInstallmentID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListRepaymentsRequest) SetPage(page *int) {
	i.Page = page
	i.require(investorListRepaymentsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListRepaymentsRequest) SetPageSize(pageSize *int) {
	i.PageSize = pageSize
	i.require(investorListRepaymentsRequestFieldPageSize)
}

// SetOrderBy sets the OrderBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListRepaymentsRequest) SetOrderBy(orderBy *string) {
	i.OrderBy = orderBy
	i.require(investorListRepaymentsRequestFieldOrderBy)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvestorListRepaymentsRequest) SetQ(q *string) {
	i.Q = q
	i.require(investorListRepaymentsRequestFieldQ)
}

var (
	clientInvestorResponseFieldID            = big.NewInt(1 << 0)
	clientInvestorResponseFieldCreatedAt     = big.NewInt(1 << 1)
	clientInvestorResponseFieldUpdatedAt     = big.NewInt(1 << 2)
	clientInvestorResponseFieldCorrelationID = big.NewInt(1 << 3)
	clientInvestorResponseFieldName          = big.NewInt(1 << 4)
	clientInvestorResponseFieldType          = big.NewInt(1 << 5)
	clientInvestorResponseFieldJurisdiction  = big.NewInt(1 << 6)
	clientInvestorResponseFieldCompanyNumber = big.NewInt(1 << 7)
	clientInvestorResponseFieldStatus        = big.NewInt(1 << 8)
)

type ClientInvestorResponse struct {
	// The ID of the client
	ID string `json:"id" url:"id"`
	// The creation date of the client
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// The last update date of the client
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`
	// The correlation ID you provided at the creation of the client
	CorrelationID *string `json:"correlation_id,omitempty" url:"correlation_id,omitempty"`
	// The name of the client
	Name string `json:"name" url:"name"`
	// The type of the client, must be one of `individual`, `corporate`
	Type ClientTypeEnum `json:"type" url:"type"`
	// The jurisdiction of the client, must be one of `eu`, `us`, `uk`
	Jurisdiction JurisdictionEnum `json:"jurisdiction" url:"jurisdiction"`
	// The company number of the client if type is `corporate`
	CompanyNumber *string `json:"company_number,omitempty" url:"company_number,omitempty"`
	// The status of the client. One of the following: `active, rejected, deactivated, pending, pending_onboarding, pre_approved, deleted, inactive`
	Status ClientStatusEnum `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ClientInvestorResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ClientInvestorResponse) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *ClientInvestorResponse) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *ClientInvestorResponse) GetCorrelationID() *string {
	if c == nil {
		return nil
	}
	return c.CorrelationID
}

func (c *ClientInvestorResponse) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *ClientInvestorResponse) GetType() ClientTypeEnum {
	if c == nil {
		return ""
	}
	return c.Type
}

func (c *ClientInvestorResponse) GetJurisdiction() JurisdictionEnum {
	if c == nil {
		return ""
	}
	return c.Jurisdiction
}

func (c *ClientInvestorResponse) GetCompanyNumber() *string {
	if c == nil {
		return nil
	}
	return c.CompanyNumber
}

func (c *ClientInvestorResponse) GetStatus() ClientStatusEnum {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *ClientInvestorResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ClientInvestorResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ClientInvestorResponse) SetID(id string) {
	c.ID = id
	c.require(clientInvestorResponseFieldID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ClientInvestorResponse) SetCreatedAt(createdAt time.Time) {
	c.CreatedAt = createdAt
	c.require(clientInvestorResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ClientInvestorResponse) SetUpdatedAt(updatedAt time.Time) {
	c.UpdatedAt = updatedAt
	c.require(clientInvestorResponseFieldUpdatedAt)
}

// SetCorrelationID sets the CorrelationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ClientInvestorResponse) SetCorrelationID(correlationID *string) {
	c.CorrelationID = correlationID
	c.require(clientInvestorResponseFieldCorrelationID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ClientInvestorResponse) SetName(name string) {
	c.Name = name
	c.require(clientInvestorResponseFieldName)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ClientInvestorResponse) SetType(type_ ClientTypeEnum) {
	c.Type = type_
	c.require(clientInvestorResponseFieldType)
}

// SetJurisdiction sets the Jurisdiction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ClientInvestorResponse) SetJurisdiction(jurisdiction JurisdictionEnum) {
	c.Jurisdiction = jurisdiction
	c.require(clientInvestorResponseFieldJurisdiction)
}

// SetCompanyNumber sets the CompanyNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ClientInvestorResponse) SetCompanyNumber(companyNumber *string) {
	c.CompanyNumber = companyNumber
	c.require(clientInvestorResponseFieldCompanyNumber)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ClientInvestorResponse) SetStatus(status ClientStatusEnum) {
	c.Status = status
	c.require(clientInvestorResponseFieldStatus)
}

func (c *ClientInvestorResponse) UnmarshalJSON(data []byte) error {
	type embed ClientInvestorResponse
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = ClientInvestorResponse(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ClientInvestorResponse) MarshalJSON() ([]byte, error) {
	type embed ClientInvestorResponse
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewDateTime(c.CreatedAt),
		UpdatedAt: internal.NewDateTime(c.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ClientInvestorResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	loanInvestorResponseFieldID                    = big.NewInt(1 << 0)
	loanInvestorResponseFieldCreatedAt             = big.NewInt(1 << 1)
	loanInvestorResponseFieldUpdatedAt             = big.NewInt(1 << 2)
	loanInvestorResponseFieldPartnerID             = big.NewInt(1 << 3)
	loanInvestorResponseFieldClientID              = big.NewInt(1 << 4)
	loanInvestorResponseFieldCurrency              = big.NewInt(1 << 5)
	loanInvestorResponseFieldAmount                = big.NewInt(1 << 6)
	loanInvestorResponseFieldStatus                = big.NewInt(1 << 7)
	loanInvestorResponseFieldIrr                   = big.NewInt(1 << 8)
	loanInvestorResponseFieldLoanDate              = big.NewInt(1 << 9)
	loanInvestorResponseFieldCurrencyRate          = big.NewInt(1 << 10)
	loanInvestorResponseFieldCorrelationID         = big.NewInt(1 << 11)
	loanInvestorResponseFieldPaymentStatus         = big.NewInt(1 << 12)
	loanInvestorResponseFieldPaymentReference      = big.NewInt(1 << 13)
	loanInvestorResponseFieldEarlySettlementDate   = big.NewInt(1 << 14)
	loanInvestorResponseFieldEarlySettlementAmount = big.NewInt(1 << 15)
	loanInvestorResponseFieldData                  = big.NewInt(1 << 16)
	loanInvestorResponseFieldClient                = big.NewInt(1 << 17)
	loanInvestorResponseFieldPaymentToTheClient    = big.NewInt(1 << 18)
)

type LoanInvestorResponse struct {
	// The ID of the loan
	ID string `json:"id" url:"id"`
	// The creation date of the loan
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// The last update date of the loan
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`
	// The ID of the partner
	PartnerID string `json:"partner_id" url:"partner_id"`
	// The ID of the client
	ClientID string `json:"client_id" url:"client_id"`
	// The currency of the loan
	Currency CurrencyEnum `json:"currency" url:"currency"`
	// The amount of the loan
	Amount string `json:"amount" url:"amount"`
	// The status of the loan
	Status LoanStatusEnum `json:"status" url:"status"`
	// The internal rate of return
	Irr *string `json:"irr,omitempty" url:"irr,omitempty"`
	// The date of the loan
	LoanDate *time.Time `json:"loan_date,omitempty" url:"loan_date,omitempty" format:"date"`
	// The currency rate conversion to EUR at the time of the loan
	CurrencyRate string `json:"currency_rate" url:"currency_rate"`
	// The correlation ID provided at the creation of the loan
	CorrelationID *string `json:"correlation_id,omitempty" url:"correlation_id,omitempty"`
	// The payment status of the loan
	PaymentStatus *LoanPaymentStatusEnum `json:"payment_status,omitempty" url:"payment_status,omitempty"`
	// The payment reference for the loan
	PaymentReference *string `json:"payment_reference,omitempty" url:"payment_reference,omitempty"`
	// The date of early settlement if the loan was settled early
	EarlySettlementDate *time.Time `json:"early_settlement_date,omitempty" url:"early_settlement_date,omitempty" format:"date"`
	// The settlement amount at early settlement if applicable
	EarlySettlementAmount *string `json:"early_settlement_amount,omitempty" url:"early_settlement_amount,omitempty"`
	// Additional data related to the loan
	Data map[string]any `json:"data,omitempty" url:"data,omitempty"`
	// The client details associated with the loan
	Client *ClientBaseInfo `json:"client" url:"client"`
	// Whether the loan disbursement is paid directly to the client (as opposed to the partner).
	PaymentToTheClient *bool `json:"payment_to_the_client,omitempty" url:"payment_to_the_client,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LoanInvestorResponse) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *LoanInvestorResponse) GetCreatedAt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.CreatedAt
}

func (l *LoanInvestorResponse) GetUpdatedAt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.UpdatedAt
}

func (l *LoanInvestorResponse) GetPartnerID() string {
	if l == nil {
		return ""
	}
	return l.PartnerID
}

func (l *LoanInvestorResponse) GetClientID() string {
	if l == nil {
		return ""
	}
	return l.ClientID
}

func (l *LoanInvestorResponse) GetCurrency() CurrencyEnum {
	if l == nil {
		return ""
	}
	return l.Currency
}

func (l *LoanInvestorResponse) GetAmount() string {
	if l == nil {
		return ""
	}
	return l.Amount
}

func (l *LoanInvestorResponse) GetStatus() LoanStatusEnum {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *LoanInvestorResponse) GetIrr() *string {
	if l == nil {
		return nil
	}
	return l.Irr
}

func (l *LoanInvestorResponse) GetLoanDate() *time.Time {
	if l == nil {
		return nil
	}
	return l.LoanDate
}

func (l *LoanInvestorResponse) GetCurrencyRate() string {
	if l == nil {
		return ""
	}
	return l.CurrencyRate
}

func (l *LoanInvestorResponse) GetCorrelationID() *string {
	if l == nil {
		return nil
	}
	return l.CorrelationID
}

func (l *LoanInvestorResponse) GetPaymentStatus() *LoanPaymentStatusEnum {
	if l == nil {
		return nil
	}
	return l.PaymentStatus
}

func (l *LoanInvestorResponse) GetPaymentReference() *string {
	if l == nil {
		return nil
	}
	return l.PaymentReference
}

func (l *LoanInvestorResponse) GetEarlySettlementDate() *time.Time {
	if l == nil {
		return nil
	}
	return l.EarlySettlementDate
}

func (l *LoanInvestorResponse) GetEarlySettlementAmount() *string {
	if l == nil {
		return nil
	}
	return l.EarlySettlementAmount
}

func (l *LoanInvestorResponse) GetData() map[string]any {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *LoanInvestorResponse) GetClient() *ClientBaseInfo {
	if l == nil {
		return nil
	}
	return l.Client
}

func (l *LoanInvestorResponse) GetPaymentToTheClient() *bool {
	if l == nil {
		return nil
	}
	return l.PaymentToTheClient
}

func (l *LoanInvestorResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LoanInvestorResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetID(id string) {
	l.ID = id
	l.require(loanInvestorResponseFieldID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetCreatedAt(createdAt time.Time) {
	l.CreatedAt = createdAt
	l.require(loanInvestorResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetUpdatedAt(updatedAt time.Time) {
	l.UpdatedAt = updatedAt
	l.require(loanInvestorResponseFieldUpdatedAt)
}

// SetPartnerID sets the PartnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetPartnerID(partnerID string) {
	l.PartnerID = partnerID
	l.require(loanInvestorResponseFieldPartnerID)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetClientID(clientID string) {
	l.ClientID = clientID
	l.require(loanInvestorResponseFieldClientID)
}

// SetCurrency sets the Currency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetCurrency(currency CurrencyEnum) {
	l.Currency = currency
	l.require(loanInvestorResponseFieldCurrency)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetAmount(amount string) {
	l.Amount = amount
	l.require(loanInvestorResponseFieldAmount)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetStatus(status LoanStatusEnum) {
	l.Status = status
	l.require(loanInvestorResponseFieldStatus)
}

// SetIrr sets the Irr field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetIrr(irr *string) {
	l.Irr = irr
	l.require(loanInvestorResponseFieldIrr)
}

// SetLoanDate sets the LoanDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetLoanDate(loanDate *time.Time) {
	l.LoanDate = loanDate
	l.require(loanInvestorResponseFieldLoanDate)
}

// SetCurrencyRate sets the CurrencyRate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetCurrencyRate(currencyRate string) {
	l.CurrencyRate = currencyRate
	l.require(loanInvestorResponseFieldCurrencyRate)
}

// SetCorrelationID sets the CorrelationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetCorrelationID(correlationID *string) {
	l.CorrelationID = correlationID
	l.require(loanInvestorResponseFieldCorrelationID)
}

// SetPaymentStatus sets the PaymentStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetPaymentStatus(paymentStatus *LoanPaymentStatusEnum) {
	l.PaymentStatus = paymentStatus
	l.require(loanInvestorResponseFieldPaymentStatus)
}

// SetPaymentReference sets the PaymentReference field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetPaymentReference(paymentReference *string) {
	l.PaymentReference = paymentReference
	l.require(loanInvestorResponseFieldPaymentReference)
}

// SetEarlySettlementDate sets the EarlySettlementDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetEarlySettlementDate(earlySettlementDate *time.Time) {
	l.EarlySettlementDate = earlySettlementDate
	l.require(loanInvestorResponseFieldEarlySettlementDate)
}

// SetEarlySettlementAmount sets the EarlySettlementAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetEarlySettlementAmount(earlySettlementAmount *string) {
	l.EarlySettlementAmount = earlySettlementAmount
	l.require(loanInvestorResponseFieldEarlySettlementAmount)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetData(data map[string]any) {
	l.Data = data
	l.require(loanInvestorResponseFieldData)
}

// SetClient sets the Client field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetClient(client *ClientBaseInfo) {
	l.Client = client
	l.require(loanInvestorResponseFieldClient)
}

// SetPaymentToTheClient sets the PaymentToTheClient field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoanInvestorResponse) SetPaymentToTheClient(paymentToTheClient *bool) {
	l.PaymentToTheClient = paymentToTheClient
	l.require(loanInvestorResponseFieldPaymentToTheClient)
}

func (l *LoanInvestorResponse) UnmarshalJSON(data []byte) error {
	type embed LoanInvestorResponse
	var unmarshaler = struct {
		embed
		CreatedAt           *internal.DateTime `json:"created_at"`
		UpdatedAt           *internal.DateTime `json:"updated_at"`
		LoanDate            *internal.Date     `json:"loan_date,omitempty"`
		EarlySettlementDate *internal.Date     `json:"early_settlement_date,omitempty"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = LoanInvestorResponse(unmarshaler.embed)
	l.CreatedAt = unmarshaler.CreatedAt.Time()
	l.UpdatedAt = unmarshaler.UpdatedAt.Time()
	l.LoanDate = unmarshaler.LoanDate.TimePtr()
	l.EarlySettlementDate = unmarshaler.EarlySettlementDate.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LoanInvestorResponse) MarshalJSON() ([]byte, error) {
	type embed LoanInvestorResponse
	var marshaler = struct {
		embed
		CreatedAt           *internal.DateTime `json:"created_at"`
		UpdatedAt           *internal.DateTime `json:"updated_at"`
		LoanDate            *internal.Date     `json:"loan_date,omitempty"`
		EarlySettlementDate *internal.Date     `json:"early_settlement_date,omitempty"`
	}{
		embed:               embed(*l),
		CreatedAt:           internal.NewDateTime(l.CreatedAt),
		UpdatedAt:           internal.NewDateTime(l.UpdatedAt),
		LoanDate:            internal.NewOptionalDate(l.LoanDate),
		EarlySettlementDate: internal.NewOptionalDate(l.EarlySettlementDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LoanInvestorResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	paginatedResponseClientInvestorResponseFieldItems       = big.NewInt(1 << 0)
	paginatedResponseClientInvestorResponseFieldPage        = big.NewInt(1 << 1)
	paginatedResponseClientInvestorResponseFieldPageSize    = big.NewInt(1 << 2)
	paginatedResponseClientInvestorResponseFieldItemsInPage = big.NewInt(1 << 3)
	paginatedResponseClientInvestorResponseFieldTotalItems  = big.NewInt(1 << 4)
	paginatedResponseClientInvestorResponseFieldTotalPages  = big.NewInt(1 << 5)
	paginatedResponseClientInvestorResponseFieldHasNext     = big.NewInt(1 << 6)
	paginatedResponseClientInvestorResponseFieldHasPrevious = big.NewInt(1 << 7)
)

type PaginatedResponseClientInvestorResponse struct {
	Items []*ClientInvestorResponse `json:"items" url:"items"`
	// Current page number
	Page *int `json:"page,omitempty" url:"page,omitempty"`
	// Number of items per page
	PageSize *int `json:"page_size,omitempty" url:"page_size,omitempty"`
	// Number of items in the current page
	ItemsInPage *int `json:"items_in_page,omitempty" url:"items_in_page,omitempty"`
	// Total number of items across all pages
	TotalItems *int `json:"total_items,omitempty" url:"total_items,omitempty"`
	// Total number of pages available
	TotalPages *int `json:"total_pages,omitempty" url:"total_pages,omitempty"`
	// Indicates if there is a next page
	HasNext *bool `json:"has_next,omitempty" url:"has_next,omitempty"`
	// Indicates if there is a previous page
	HasPrevious *bool `json:"has_previous,omitempty" url:"has_previous,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginatedResponseClientInvestorResponse) GetItems() []*ClientInvestorResponse {
	if p == nil {
		return nil
	}
	return p.Items
}

func (p *PaginatedResponseClientInvestorResponse) GetPage() *int {
	if p == nil {
		return nil
	}
	return p.Page
}

func (p *PaginatedResponseClientInvestorResponse) GetPageSize() *int {
	if p == nil {
		return nil
	}
	return p.PageSize
}

func (p *PaginatedResponseClientInvestorResponse) GetItemsInPage() *int {
	if p == nil {
		return nil
	}
	return p.ItemsInPage
}

func (p *PaginatedResponseClientInvestorResponse) GetTotalItems() *int {
	if p == nil {
		return nil
	}
	return p.TotalItems
}

func (p *PaginatedResponseClientInvestorResponse) GetTotalPages() *int {
	if p == nil {
		return nil
	}
	return p.TotalPages
}

func (p *PaginatedResponseClientInvestorResponse) GetHasNext() *bool {
	if p == nil {
		return nil
	}
	return p.HasNext
}

func (p *PaginatedResponseClientInvestorResponse) GetHasPrevious() *bool {
	if p == nil {
		return nil
	}
	return p.HasPrevious
}

func (p *PaginatedResponseClientInvestorResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PaginatedResponseClientInvestorResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseClientInvestorResponse) SetItems(items []*ClientInvestorResponse) {
	p.Items = items
	p.require(paginatedResponseClientInvestorResponseFieldItems)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseClientInvestorResponse) SetPage(page *int) {
	p.Page = page
	p.require(paginatedResponseClientInvestorResponseFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseClientInvestorResponse) SetPageSize(pageSize *int) {
	p.PageSize = pageSize
	p.require(paginatedResponseClientInvestorResponseFieldPageSize)
}

// SetItemsInPage sets the ItemsInPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseClientInvestorResponse) SetItemsInPage(itemsInPage *int) {
	p.ItemsInPage = itemsInPage
	p.require(paginatedResponseClientInvestorResponseFieldItemsInPage)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseClientInvestorResponse) SetTotalItems(totalItems *int) {
	p.TotalItems = totalItems
	p.require(paginatedResponseClientInvestorResponseFieldTotalItems)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseClientInvestorResponse) SetTotalPages(totalPages *int) {
	p.TotalPages = totalPages
	p.require(paginatedResponseClientInvestorResponseFieldTotalPages)
}

// SetHasNext sets the HasNext field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseClientInvestorResponse) SetHasNext(hasNext *bool) {
	p.HasNext = hasNext
	p.require(paginatedResponseClientInvestorResponseFieldHasNext)
}

// SetHasPrevious sets the HasPrevious field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseClientInvestorResponse) SetHasPrevious(hasPrevious *bool) {
	p.HasPrevious = hasPrevious
	p.require(paginatedResponseClientInvestorResponseFieldHasPrevious)
}

func (p *PaginatedResponseClientInvestorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedResponseClientInvestorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedResponseClientInvestorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedResponseClientInvestorResponse) MarshalJSON() ([]byte, error) {
	type embed PaginatedResponseClientInvestorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginatedResponseClientInvestorResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	paginatedResponseLoanInvestorResponseFieldItems       = big.NewInt(1 << 0)
	paginatedResponseLoanInvestorResponseFieldPage        = big.NewInt(1 << 1)
	paginatedResponseLoanInvestorResponseFieldPageSize    = big.NewInt(1 << 2)
	paginatedResponseLoanInvestorResponseFieldItemsInPage = big.NewInt(1 << 3)
	paginatedResponseLoanInvestorResponseFieldTotalItems  = big.NewInt(1 << 4)
	paginatedResponseLoanInvestorResponseFieldTotalPages  = big.NewInt(1 << 5)
	paginatedResponseLoanInvestorResponseFieldHasNext     = big.NewInt(1 << 6)
	paginatedResponseLoanInvestorResponseFieldHasPrevious = big.NewInt(1 << 7)
)

type PaginatedResponseLoanInvestorResponse struct {
	Items []*LoanInvestorResponse `json:"items" url:"items"`
	// Current page number
	Page *int `json:"page,omitempty" url:"page,omitempty"`
	// Number of items per page
	PageSize *int `json:"page_size,omitempty" url:"page_size,omitempty"`
	// Number of items in the current page
	ItemsInPage *int `json:"items_in_page,omitempty" url:"items_in_page,omitempty"`
	// Total number of items across all pages
	TotalItems *int `json:"total_items,omitempty" url:"total_items,omitempty"`
	// Total number of pages available
	TotalPages *int `json:"total_pages,omitempty" url:"total_pages,omitempty"`
	// Indicates if there is a next page
	HasNext *bool `json:"has_next,omitempty" url:"has_next,omitempty"`
	// Indicates if there is a previous page
	HasPrevious *bool `json:"has_previous,omitempty" url:"has_previous,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginatedResponseLoanInvestorResponse) GetItems() []*LoanInvestorResponse {
	if p == nil {
		return nil
	}
	return p.Items
}

func (p *PaginatedResponseLoanInvestorResponse) GetPage() *int {
	if p == nil {
		return nil
	}
	return p.Page
}

func (p *PaginatedResponseLoanInvestorResponse) GetPageSize() *int {
	if p == nil {
		return nil
	}
	return p.PageSize
}

func (p *PaginatedResponseLoanInvestorResponse) GetItemsInPage() *int {
	if p == nil {
		return nil
	}
	return p.ItemsInPage
}

func (p *PaginatedResponseLoanInvestorResponse) GetTotalItems() *int {
	if p == nil {
		return nil
	}
	return p.TotalItems
}

func (p *PaginatedResponseLoanInvestorResponse) GetTotalPages() *int {
	if p == nil {
		return nil
	}
	return p.TotalPages
}

func (p *PaginatedResponseLoanInvestorResponse) GetHasNext() *bool {
	if p == nil {
		return nil
	}
	return p.HasNext
}

func (p *PaginatedResponseLoanInvestorResponse) GetHasPrevious() *bool {
	if p == nil {
		return nil
	}
	return p.HasPrevious
}

func (p *PaginatedResponseLoanInvestorResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PaginatedResponseLoanInvestorResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseLoanInvestorResponse) SetItems(items []*LoanInvestorResponse) {
	p.Items = items
	p.require(paginatedResponseLoanInvestorResponseFieldItems)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseLoanInvestorResponse) SetPage(page *int) {
	p.Page = page
	p.require(paginatedResponseLoanInvestorResponseFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseLoanInvestorResponse) SetPageSize(pageSize *int) {
	p.PageSize = pageSize
	p.require(paginatedResponseLoanInvestorResponseFieldPageSize)
}

// SetItemsInPage sets the ItemsInPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseLoanInvestorResponse) SetItemsInPage(itemsInPage *int) {
	p.ItemsInPage = itemsInPage
	p.require(paginatedResponseLoanInvestorResponseFieldItemsInPage)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseLoanInvestorResponse) SetTotalItems(totalItems *int) {
	p.TotalItems = totalItems
	p.require(paginatedResponseLoanInvestorResponseFieldTotalItems)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseLoanInvestorResponse) SetTotalPages(totalPages *int) {
	p.TotalPages = totalPages
	p.require(paginatedResponseLoanInvestorResponseFieldTotalPages)
}

// SetHasNext sets the HasNext field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseLoanInvestorResponse) SetHasNext(hasNext *bool) {
	p.HasNext = hasNext
	p.require(paginatedResponseLoanInvestorResponseFieldHasNext)
}

// SetHasPrevious sets the HasPrevious field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseLoanInvestorResponse) SetHasPrevious(hasPrevious *bool) {
	p.HasPrevious = hasPrevious
	p.require(paginatedResponseLoanInvestorResponseFieldHasPrevious)
}

func (p *PaginatedResponseLoanInvestorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedResponseLoanInvestorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedResponseLoanInvestorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedResponseLoanInvestorResponse) MarshalJSON() ([]byte, error) {
	type embed PaginatedResponseLoanInvestorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginatedResponseLoanInvestorResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
