// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersRecoveryCreatePayload(t *testing.T) {
	t.Run("SetLoanID", func(t *testing.T) {
		obj := &RecoveryCreatePayload{}
		var fernTestValueLoanID string
		obj.SetLoanID(fernTestValueLoanID)
		assert.Equal(t, fernTestValueLoanID, obj.LoanID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAmount", func(t *testing.T) {
		obj := &RecoveryCreatePayload{}
		var fernTestValueAmount *RecoveryCreatePayloadAmount
		obj.SetAmount(fernTestValueAmount)
		assert.Equal(t, fernTestValueAmount, obj.Amount)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCurrency", func(t *testing.T) {
		obj := &RecoveryCreatePayload{}
		var fernTestValueCurrency CurrencyEnum
		obj.SetCurrency(fernTestValueCurrency)
		assert.Equal(t, fernTestValueCurrency, obj.Currency)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRecoveryDate", func(t *testing.T) {
		obj := &RecoveryCreatePayload{}
		var fernTestValueRecoveryDate time.Time
		obj.SetRecoveryDate(fernTestValueRecoveryDate)
		assert.Equal(t, fernTestValueRecoveryDate, obj.RecoveryDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNotes", func(t *testing.T) {
		obj := &RecoveryCreatePayload{}
		var fernTestValueNotes *string
		obj.SetNotes(fernTestValueNotes)
		assert.Equal(t, fernTestValueNotes, obj.Notes)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitRecoveryCreatePayload(t *testing.T) {
	t.Run("SetLoanID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryCreatePayload{}
		var fernTestValueLoanID string

		// Act
		obj.SetLoanID(fernTestValueLoanID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAmount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryCreatePayload{}
		var fernTestValueAmount *RecoveryCreatePayloadAmount

		// Act
		obj.SetAmount(fernTestValueAmount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCurrency_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryCreatePayload{}
		var fernTestValueCurrency CurrencyEnum

		// Act
		obj.SetCurrency(fernTestValueCurrency)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRecoveryDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryCreatePayload{}
		var fernTestValueRecoveryDate time.Time

		// Act
		obj.SetRecoveryDate(fernTestValueRecoveryDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNotes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryCreatePayload{}
		var fernTestValueNotes *string

		// Act
		obj.SetNotes(fernTestValueNotes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListRecoveriesRequest(t *testing.T) {
	t.Run("SetClientID", func(t *testing.T) {
		obj := &ListRecoveriesRequest{}
		var fernTestValueClientID *string
		obj.SetClientID(fernTestValueClientID)
		assert.Equal(t, fernTestValueClientID, obj.ClientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLoanID", func(t *testing.T) {
		obj := &ListRecoveriesRequest{}
		var fernTestValueLoanID *string
		obj.SetLoanID(fernTestValueLoanID)
		assert.Equal(t, fernTestValueLoanID, obj.LoanID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &ListRecoveriesRequest{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPageSize", func(t *testing.T) {
		obj := &ListRecoveriesRequest{}
		var fernTestValuePageSize *int
		obj.SetPageSize(fernTestValuePageSize)
		assert.Equal(t, fernTestValuePageSize, obj.PageSize)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrderBy", func(t *testing.T) {
		obj := &ListRecoveriesRequest{}
		var fernTestValueOrderBy *string
		obj.SetOrderBy(fernTestValueOrderBy)
		assert.Equal(t, fernTestValueOrderBy, obj.OrderBy)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQ", func(t *testing.T) {
		obj := &ListRecoveriesRequest{}
		var fernTestValueQ *string
		obj.SetQ(fernTestValueQ)
		assert.Equal(t, fernTestValueQ, obj.Q)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListRecoveriesRequest(t *testing.T) {
	t.Run("SetClientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecoveriesRequest{}
		var fernTestValueClientID *string

		// Act
		obj.SetClientID(fernTestValueClientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLoanID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecoveriesRequest{}
		var fernTestValueLoanID *string

		// Act
		obj.SetLoanID(fernTestValueLoanID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecoveriesRequest{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPageSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecoveriesRequest{}
		var fernTestValuePageSize *int

		// Act
		obj.SetPageSize(fernTestValuePageSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrderBy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecoveriesRequest{}
		var fernTestValueOrderBy *string

		// Act
		obj.SetOrderBy(fernTestValueOrderBy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQ_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecoveriesRequest{}
		var fernTestValueQ *string

		// Act
		obj.SetQ(fernTestValueQ)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPaginatedResponseRecoveryResponse(t *testing.T) {
	t.Run("SetItems", func(t *testing.T) {
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValueItems []*RecoveryResponse
		obj.SetItems(fernTestValueItems)
		assert.Equal(t, fernTestValueItems, obj.Items)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPageSize", func(t *testing.T) {
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValuePageSize *int
		obj.SetPageSize(fernTestValuePageSize)
		assert.Equal(t, fernTestValuePageSize, obj.PageSize)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetItemsInPage", func(t *testing.T) {
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValueItemsInPage *int
		obj.SetItemsInPage(fernTestValueItemsInPage)
		assert.Equal(t, fernTestValueItemsInPage, obj.ItemsInPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTotalItems", func(t *testing.T) {
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValueTotalItems *int
		obj.SetTotalItems(fernTestValueTotalItems)
		assert.Equal(t, fernTestValueTotalItems, obj.TotalItems)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTotalPages", func(t *testing.T) {
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValueTotalPages *int
		obj.SetTotalPages(fernTestValueTotalPages)
		assert.Equal(t, fernTestValueTotalPages, obj.TotalPages)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHasNext", func(t *testing.T) {
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValueHasNext *bool
		obj.SetHasNext(fernTestValueHasNext)
		assert.Equal(t, fernTestValueHasNext, obj.HasNext)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHasPrevious", func(t *testing.T) {
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValueHasPrevious *bool
		obj.SetHasPrevious(fernTestValueHasPrevious)
		assert.Equal(t, fernTestValueHasPrevious, obj.HasPrevious)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersPaginatedResponseRecoveryResponse(t *testing.T) {
	t.Run("GetItems", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var expected []*RecoveryResponse
		obj.Items = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetItems(), "getter should return the property value")
	})

	t.Run("GetItems_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		obj.Items = nil

		// Act & Assert
		assert.Nil(t, obj.GetItems(), "getter should return nil when property is nil")
	})

	t.Run("GetItems_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseRecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetItems() // Should return zero value
	})

	t.Run("GetPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var expected *int
		obj.Page = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPage(), "getter should return the property value")
	})

	t.Run("GetPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		obj.Page = nil

		// Act & Assert
		assert.Nil(t, obj.GetPage(), "getter should return nil when property is nil")
	})

	t.Run("GetPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseRecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPage() // Should return zero value
	})

	t.Run("GetPageSize", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var expected *int
		obj.PageSize = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPageSize(), "getter should return the property value")
	})

	t.Run("GetPageSize_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		obj.PageSize = nil

		// Act & Assert
		assert.Nil(t, obj.GetPageSize(), "getter should return nil when property is nil")
	})

	t.Run("GetPageSize_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseRecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPageSize() // Should return zero value
	})

	t.Run("GetItemsInPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var expected *int
		obj.ItemsInPage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetItemsInPage(), "getter should return the property value")
	})

	t.Run("GetItemsInPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		obj.ItemsInPage = nil

		// Act & Assert
		assert.Nil(t, obj.GetItemsInPage(), "getter should return nil when property is nil")
	})

	t.Run("GetItemsInPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseRecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetItemsInPage() // Should return zero value
	})

	t.Run("GetTotalItems", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var expected *int
		obj.TotalItems = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTotalItems(), "getter should return the property value")
	})

	t.Run("GetTotalItems_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		obj.TotalItems = nil

		// Act & Assert
		assert.Nil(t, obj.GetTotalItems(), "getter should return nil when property is nil")
	})

	t.Run("GetTotalItems_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseRecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTotalItems() // Should return zero value
	})

	t.Run("GetTotalPages", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var expected *int
		obj.TotalPages = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTotalPages(), "getter should return the property value")
	})

	t.Run("GetTotalPages_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		obj.TotalPages = nil

		// Act & Assert
		assert.Nil(t, obj.GetTotalPages(), "getter should return nil when property is nil")
	})

	t.Run("GetTotalPages_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseRecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTotalPages() // Should return zero value
	})

	t.Run("GetHasNext", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var expected *bool
		obj.HasNext = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHasNext(), "getter should return the property value")
	})

	t.Run("GetHasNext_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		obj.HasNext = nil

		// Act & Assert
		assert.Nil(t, obj.GetHasNext(), "getter should return nil when property is nil")
	})

	t.Run("GetHasNext_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseRecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHasNext() // Should return zero value
	})

	t.Run("GetHasPrevious", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var expected *bool
		obj.HasPrevious = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHasPrevious(), "getter should return the property value")
	})

	t.Run("GetHasPrevious_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		obj.HasPrevious = nil

		// Act & Assert
		assert.Nil(t, obj.GetHasPrevious(), "getter should return nil when property is nil")
	})

	t.Run("GetHasPrevious_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseRecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHasPrevious() // Should return zero value
	})

}

func TestSettersMarkExplicitPaginatedResponseRecoveryResponse(t *testing.T) {
	t.Run("SetItems_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValueItems []*RecoveryResponse

		// Act
		obj.SetItems(fernTestValueItems)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPageSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValuePageSize *int

		// Act
		obj.SetPageSize(fernTestValuePageSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetItemsInPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValueItemsInPage *int

		// Act
		obj.SetItemsInPage(fernTestValueItemsInPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTotalItems_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValueTotalItems *int

		// Act
		obj.SetTotalItems(fernTestValueTotalItems)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTotalPages_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValueTotalPages *int

		// Act
		obj.SetTotalPages(fernTestValueTotalPages)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHasNext_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValueHasNext *bool

		// Act
		obj.SetHasNext(fernTestValueHasNext)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHasPrevious_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}
		var fernTestValueHasPrevious *bool

		// Act
		obj.SetHasPrevious(fernTestValueHasPrevious)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRecoveryResponse(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &RecoveryResponse{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &RecoveryResponse{}
		var fernTestValueCreatedAt time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdatedAt", func(t *testing.T) {
		obj := &RecoveryResponse{}
		var fernTestValueUpdatedAt time.Time
		obj.SetUpdatedAt(fernTestValueUpdatedAt)
		assert.Equal(t, fernTestValueUpdatedAt, obj.UpdatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPartnerID", func(t *testing.T) {
		obj := &RecoveryResponse{}
		var fernTestValuePartnerID string
		obj.SetPartnerID(fernTestValuePartnerID)
		assert.Equal(t, fernTestValuePartnerID, obj.PartnerID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetClientID", func(t *testing.T) {
		obj := &RecoveryResponse{}
		var fernTestValueClientID string
		obj.SetClientID(fernTestValueClientID)
		assert.Equal(t, fernTestValueClientID, obj.ClientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLoanID", func(t *testing.T) {
		obj := &RecoveryResponse{}
		var fernTestValueLoanID string
		obj.SetLoanID(fernTestValueLoanID)
		assert.Equal(t, fernTestValueLoanID, obj.LoanID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAmount", func(t *testing.T) {
		obj := &RecoveryResponse{}
		var fernTestValueAmount string
		obj.SetAmount(fernTestValueAmount)
		assert.Equal(t, fernTestValueAmount, obj.Amount)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCurrency", func(t *testing.T) {
		obj := &RecoveryResponse{}
		var fernTestValueCurrency CurrencyEnum
		obj.SetCurrency(fernTestValueCurrency)
		assert.Equal(t, fernTestValueCurrency, obj.Currency)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRecoveryDate", func(t *testing.T) {
		obj := &RecoveryResponse{}
		var fernTestValueRecoveryDate time.Time
		obj.SetRecoveryDate(fernTestValueRecoveryDate)
		assert.Equal(t, fernTestValueRecoveryDate, obj.RecoveryDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNotes", func(t *testing.T) {
		obj := &RecoveryResponse{}
		var fernTestValueNotes *string
		obj.SetNotes(fernTestValueNotes)
		assert.Equal(t, fernTestValueNotes, obj.Notes)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersRecoveryResponse(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var expected string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var expected time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetUpdatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var expected time.Time
		obj.UpdatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUpdatedAt(), "getter should return the property value")
	})

	t.Run("GetUpdatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUpdatedAt() // Should return zero value
	})

	t.Run("GetPartnerID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var expected string
		obj.PartnerID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPartnerID(), "getter should return the property value")
	})

	t.Run("GetPartnerID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPartnerID() // Should return zero value
	})

	t.Run("GetClientID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var expected string
		obj.ClientID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetClientID(), "getter should return the property value")
	})

	t.Run("GetClientID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetClientID() // Should return zero value
	})

	t.Run("GetLoanID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var expected string
		obj.LoanID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLoanID(), "getter should return the property value")
	})

	t.Run("GetLoanID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLoanID() // Should return zero value
	})

	t.Run("GetAmount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var expected string
		obj.Amount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAmount(), "getter should return the property value")
	})

	t.Run("GetAmount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAmount() // Should return zero value
	})

	t.Run("GetCurrency", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var expected CurrencyEnum
		obj.Currency = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCurrency(), "getter should return the property value")
	})

	t.Run("GetCurrency_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCurrency() // Should return zero value
	})

	t.Run("GetRecoveryDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var expected time.Time
		obj.RecoveryDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRecoveryDate(), "getter should return the property value")
	})

	t.Run("GetRecoveryDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRecoveryDate() // Should return zero value
	})

	t.Run("GetNotes", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var expected *string
		obj.Notes = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNotes(), "getter should return the property value")
	})

	t.Run("GetNotes_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		obj.Notes = nil

		// Act & Assert
		assert.Nil(t, obj.GetNotes(), "getter should return nil when property is nil")
	})

	t.Run("GetNotes_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNotes() // Should return zero value
	})

}

func TestSettersMarkExplicitRecoveryResponse(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var fernTestValueCreatedAt time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var fernTestValueUpdatedAt time.Time

		// Act
		obj.SetUpdatedAt(fernTestValueUpdatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPartnerID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var fernTestValuePartnerID string

		// Act
		obj.SetPartnerID(fernTestValuePartnerID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetClientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var fernTestValueClientID string

		// Act
		obj.SetClientID(fernTestValueClientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLoanID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var fernTestValueLoanID string

		// Act
		obj.SetLoanID(fernTestValueLoanID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAmount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var fernTestValueAmount string

		// Act
		obj.SetAmount(fernTestValueAmount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCurrency_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var fernTestValueCurrency CurrencyEnum

		// Act
		obj.SetCurrency(fernTestValueCurrency)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRecoveryDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var fernTestValueRecoveryDate time.Time

		// Act
		obj.SetRecoveryDate(fernTestValueRecoveryDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNotes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}
		var fernTestValueNotes *string

		// Act
		obj.SetNotes(fernTestValueNotes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestGettersRecoveryCreatePayloadAmount(t *testing.T) {
	t.Run("GetDouble", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryCreatePayloadAmount{}
		var expected float64
		obj.Double = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDouble(), "getter should return the property value")
	})

	t.Run("GetDouble_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryCreatePayloadAmount
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDouble() // Should return zero value
	})

	t.Run("GetString", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryCreatePayloadAmount{}
		var expected string
		obj.String = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetString(), "getter should return the property value")
	})

	t.Run("GetString_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryCreatePayloadAmount
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetString() // Should return zero value
	})

}

func TestJSONMarshalingPaginatedResponseRecoveryResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PaginatedResponseRecoveryResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled PaginatedResponseRecoveryResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj PaginatedResponseRecoveryResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj PaginatedResponseRecoveryResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingRecoveryResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecoveryResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled RecoveryResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj RecoveryResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj RecoveryResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringPaginatedResponseRecoveryResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &PaginatedResponseRecoveryResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseRecoveryResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringRecoveryResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &RecoveryResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesPaginatedResponseRecoveryResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &PaginatedResponseRecoveryResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PaginatedResponseRecoveryResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesRecoveryResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &RecoveryResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecoveryResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
