// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	big "math/big"
	time "time"
)

var (
	bulkRepaymentCreatePayloadFieldRepayments = big.NewInt(1 << 0)
)

type BulkRepaymentCreatePayload struct {
	// List of repayments to create (max 10000)
	Repayments []*BulkRepaymentItemPayload `json:"repayments" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BulkRepaymentCreatePayload) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetRepayments sets the Repayments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentCreatePayload) SetRepayments(repayments []*BulkRepaymentItemPayload) {
	b.Repayments = repayments
	b.require(bulkRepaymentCreatePayloadFieldRepayments)
}

func (b *BulkRepaymentCreatePayload) UnmarshalJSON(data []byte) error {
	type unmarshaler BulkRepaymentCreatePayload
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*b = BulkRepaymentCreatePayload(body)
	return nil
}

func (b *BulkRepaymentCreatePayload) MarshalJSON() ([]byte, error) {
	type embed BulkRepaymentCreatePayload
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	repaymentCreatePayloadFieldInstallmentID     = big.NewInt(1 << 0)
	repaymentCreatePayloadFieldLoanID            = big.NewInt(1 << 1)
	repaymentCreatePayloadFieldCorrelationID     = big.NewInt(1 << 2)
	repaymentCreatePayloadFieldAmount            = big.NewInt(1 << 3)
	repaymentCreatePayloadFieldRepaymentDate     = big.NewInt(1 << 4)
	repaymentCreatePayloadFieldData              = big.NewInt(1 << 5)
	repaymentCreatePayloadFieldIsEarlySettlement = big.NewInt(1 << 6)
)

type RepaymentCreatePayload struct {
	// ID of the installment
	InstallmentID *string `json:"-" url:"installment_id,omitempty"`
	// ID of the associated Loan
	LoanID *string `json:"-" url:"loan_id,omitempty"`
	// Correlation ID of associated loan
	CorrelationID *string `json:"-" url:"correlation_id,omitempty"`
	// The amount of payment made for installment
	Amount *RepaymentCreatePayloadAmount `json:"amount" url:"-"`
	// Please provide the repayment_date if it differs from the time you log this repayment. Otherwise, it will be automatically set.
	RepaymentDate *time.Time `json:"repayment_date,omitempty" url:"-"`
	// Additional metadata related to the repayment
	Data map[string]any `json:"data,omitempty" url:"-"`
	// Indicates if this repayment is for early settlement
	IsEarlySettlement *bool `json:"is_early_settlement,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RepaymentCreatePayload) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetInstallmentID sets the InstallmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentCreatePayload) SetInstallmentID(installmentID *string) {
	r.InstallmentID = installmentID
	r.require(repaymentCreatePayloadFieldInstallmentID)
}

// SetLoanID sets the LoanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentCreatePayload) SetLoanID(loanID *string) {
	r.LoanID = loanID
	r.require(repaymentCreatePayloadFieldLoanID)
}

// SetCorrelationID sets the CorrelationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentCreatePayload) SetCorrelationID(correlationID *string) {
	r.CorrelationID = correlationID
	r.require(repaymentCreatePayloadFieldCorrelationID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentCreatePayload) SetAmount(amount *RepaymentCreatePayloadAmount) {
	r.Amount = amount
	r.require(repaymentCreatePayloadFieldAmount)
}

// SetRepaymentDate sets the RepaymentDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentCreatePayload) SetRepaymentDate(repaymentDate *time.Time) {
	r.RepaymentDate = repaymentDate
	r.require(repaymentCreatePayloadFieldRepaymentDate)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentCreatePayload) SetData(data map[string]any) {
	r.Data = data
	r.require(repaymentCreatePayloadFieldData)
}

// SetIsEarlySettlement sets the IsEarlySettlement field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentCreatePayload) SetIsEarlySettlement(isEarlySettlement *bool) {
	r.IsEarlySettlement = isEarlySettlement
	r.require(repaymentCreatePayloadFieldIsEarlySettlement)
}

func (r *RepaymentCreatePayload) UnmarshalJSON(data []byte) error {
	type unmarshaler RepaymentCreatePayload
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RepaymentCreatePayload(body)
	return nil
}

func (r *RepaymentCreatePayload) MarshalJSON() ([]byte, error) {
	type embed RepaymentCreatePayload
	var marshaler = struct {
		embed
		RepaymentDate *internal.DateTime `json:"repayment_date,omitempty"`
	}{
		embed:         embed(*r),
		RepaymentDate: internal.NewOptionalDateTime(r.RepaymentDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getBulkRepaymentStatusRequestFieldTaskID = big.NewInt(1 << 0)
)

type GetBulkRepaymentStatusRequest struct {
	TaskID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetBulkRepaymentStatusRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTaskID sets the TaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBulkRepaymentStatusRequest) SetTaskID(taskID string) {
	g.TaskID = taskID
	g.require(getBulkRepaymentStatusRequestFieldTaskID)
}

var (
	listRepaymentLogsRequestFieldClientID      = big.NewInt(1 << 0)
	listRepaymentLogsRequestFieldLoanID        = big.NewInt(1 << 1)
	listRepaymentLogsRequestFieldInstallmentID = big.NewInt(1 << 2)
	listRepaymentLogsRequestFieldPage          = big.NewInt(1 << 3)
	listRepaymentLogsRequestFieldPageSize      = big.NewInt(1 << 4)
	listRepaymentLogsRequestFieldOrderBy       = big.NewInt(1 << 5)
	listRepaymentLogsRequestFieldQ             = big.NewInt(1 << 6)
)

type ListRepaymentLogsRequest struct {
	ClientID      *string `json:"-" url:"client_id,omitempty"`
	LoanID        *string `json:"-" url:"loan_id,omitempty"`
	InstallmentID *string `json:"-" url:"installment_id,omitempty"`
	Page          *int    `json:"-" url:"page,omitempty"`
	PageSize      *int    `json:"-" url:"page_size,omitempty"`
	// Field to order the results by, e.g., 'created_at:desc,updated_at:asc'
	OrderBy *string `json:"-" url:"order_by,omitempty"`
	// Query string for filtering. Format: "field:operator:value;...". Supported fields: id, client_id, loan_id, installment_id, created_at, client.name, client.correlation_id. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.
	Q *string `json:"-" url:"q,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListRepaymentLogsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRepaymentLogsRequest) SetClientID(clientID *string) {
	l.ClientID = clientID
	l.require(listRepaymentLogsRequestFieldClientID)
}

// SetLoanID sets the LoanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRepaymentLogsRequest) SetLoanID(loanID *string) {
	l.LoanID = loanID
	l.require(listRepaymentLogsRequestFieldLoanID)
}

// SetInstallmentID sets the InstallmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRepaymentLogsRequest) SetInstallmentID(installmentID *string) {
	l.InstallmentID = installmentID
	l.require(listRepaymentLogsRequestFieldInstallmentID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRepaymentLogsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listRepaymentLogsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRepaymentLogsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listRepaymentLogsRequestFieldPageSize)
}

// SetOrderBy sets the OrderBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRepaymentLogsRequest) SetOrderBy(orderBy *string) {
	l.OrderBy = orderBy
	l.require(listRepaymentLogsRequestFieldOrderBy)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRepaymentLogsRequest) SetQ(q *string) {
	l.Q = q
	l.require(listRepaymentLogsRequestFieldQ)
}

var (
	bulkRepaymentItemPayloadFieldAmount            = big.NewInt(1 << 0)
	bulkRepaymentItemPayloadFieldRepaymentDate     = big.NewInt(1 << 1)
	bulkRepaymentItemPayloadFieldData              = big.NewInt(1 << 2)
	bulkRepaymentItemPayloadFieldIsEarlySettlement = big.NewInt(1 << 3)
	bulkRepaymentItemPayloadFieldInstallmentID     = big.NewInt(1 << 4)
	bulkRepaymentItemPayloadFieldLoanID            = big.NewInt(1 << 5)
	bulkRepaymentItemPayloadFieldCorrelationID     = big.NewInt(1 << 6)
)

type BulkRepaymentItemPayload struct {
	// The amount of payment made for installment
	Amount *BulkRepaymentItemPayloadAmount `json:"amount" url:"amount"`
	// Please provide the repayment_date if it differs from the time you log this repayment. Otherwise, it will be automatically set.
	RepaymentDate *time.Time `json:"repayment_date,omitempty" url:"repayment_date,omitempty"`
	// Additional metadata related to the repayment
	Data map[string]any `json:"data,omitempty" url:"data,omitempty"`
	// Indicates if this repayment is for early settlement
	IsEarlySettlement *bool `json:"is_early_settlement,omitempty" url:"is_early_settlement,omitempty"`
	// ID of the installment to make payment for
	InstallmentID *string `json:"installment_id,omitempty" url:"installment_id,omitempty"`
	// ID of the associated loan (alternative to installment_id)
	LoanID *string `json:"loan_id,omitempty" url:"loan_id,omitempty"`
	// Correlation ID of associated loan (alternative identifier)
	CorrelationID *string `json:"correlation_id,omitempty" url:"correlation_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BulkRepaymentItemPayload) GetAmount() *BulkRepaymentItemPayloadAmount {
	if b == nil {
		return nil
	}
	return b.Amount
}

func (b *BulkRepaymentItemPayload) GetRepaymentDate() *time.Time {
	if b == nil {
		return nil
	}
	return b.RepaymentDate
}

func (b *BulkRepaymentItemPayload) GetData() map[string]any {
	if b == nil {
		return nil
	}
	return b.Data
}

func (b *BulkRepaymentItemPayload) GetIsEarlySettlement() *bool {
	if b == nil {
		return nil
	}
	return b.IsEarlySettlement
}

func (b *BulkRepaymentItemPayload) GetInstallmentID() *string {
	if b == nil {
		return nil
	}
	return b.InstallmentID
}

func (b *BulkRepaymentItemPayload) GetLoanID() *string {
	if b == nil {
		return nil
	}
	return b.LoanID
}

func (b *BulkRepaymentItemPayload) GetCorrelationID() *string {
	if b == nil {
		return nil
	}
	return b.CorrelationID
}

func (b *BulkRepaymentItemPayload) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BulkRepaymentItemPayload) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemPayload) SetAmount(amount *BulkRepaymentItemPayloadAmount) {
	b.Amount = amount
	b.require(bulkRepaymentItemPayloadFieldAmount)
}

// SetRepaymentDate sets the RepaymentDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemPayload) SetRepaymentDate(repaymentDate *time.Time) {
	b.RepaymentDate = repaymentDate
	b.require(bulkRepaymentItemPayloadFieldRepaymentDate)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemPayload) SetData(data map[string]any) {
	b.Data = data
	b.require(bulkRepaymentItemPayloadFieldData)
}

// SetIsEarlySettlement sets the IsEarlySettlement field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemPayload) SetIsEarlySettlement(isEarlySettlement *bool) {
	b.IsEarlySettlement = isEarlySettlement
	b.require(bulkRepaymentItemPayloadFieldIsEarlySettlement)
}

// SetInstallmentID sets the InstallmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemPayload) SetInstallmentID(installmentID *string) {
	b.InstallmentID = installmentID
	b.require(bulkRepaymentItemPayloadFieldInstallmentID)
}

// SetLoanID sets the LoanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemPayload) SetLoanID(loanID *string) {
	b.LoanID = loanID
	b.require(bulkRepaymentItemPayloadFieldLoanID)
}

// SetCorrelationID sets the CorrelationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemPayload) SetCorrelationID(correlationID *string) {
	b.CorrelationID = correlationID
	b.require(bulkRepaymentItemPayloadFieldCorrelationID)
}

func (b *BulkRepaymentItemPayload) UnmarshalJSON(data []byte) error {
	type embed BulkRepaymentItemPayload
	var unmarshaler = struct {
		embed
		RepaymentDate *internal.DateTime `json:"repayment_date,omitempty"`
	}{
		embed: embed(*b),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*b = BulkRepaymentItemPayload(unmarshaler.embed)
	b.RepaymentDate = unmarshaler.RepaymentDate.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BulkRepaymentItemPayload) MarshalJSON() ([]byte, error) {
	type embed BulkRepaymentItemPayload
	var marshaler = struct {
		embed
		RepaymentDate *internal.DateTime `json:"repayment_date,omitempty"`
	}{
		embed:         embed(*b),
		RepaymentDate: internal.NewOptionalDateTime(b.RepaymentDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BulkRepaymentItemPayload) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

// The amount of payment made for installment
type BulkRepaymentItemPayloadAmount struct {
	Double float64
	String string

	typ string
}

func (b *BulkRepaymentItemPayloadAmount) GetDouble() float64 {
	if b == nil {
		return 0
	}
	return b.Double
}

func (b *BulkRepaymentItemPayloadAmount) GetString() string {
	if b == nil {
		return ""
	}
	return b.String
}

func (b *BulkRepaymentItemPayloadAmount) UnmarshalJSON(data []byte) error {
	var valueDouble float64
	if err := json.Unmarshal(data, &valueDouble); err == nil {
		b.typ = "Double"
		b.Double = valueDouble
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		b.typ = "String"
		b.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, b)
}

func (b BulkRepaymentItemPayloadAmount) MarshalJSON() ([]byte, error) {
	if b.typ == "Double" || b.Double != 0 {
		return json.Marshal(b.Double)
	}
	if b.typ == "String" || b.String != "" {
		return json.Marshal(b.String)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", b)
}

type BulkRepaymentItemPayloadAmountVisitor interface {
	VisitDouble(float64) error
	VisitString(string) error
}

func (b *BulkRepaymentItemPayloadAmount) Accept(visitor BulkRepaymentItemPayloadAmountVisitor) error {
	if b.typ == "Double" || b.Double != 0 {
		return visitor.VisitDouble(b.Double)
	}
	if b.typ == "String" || b.String != "" {
		return visitor.VisitString(b.String)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", b)
}

var (
	bulkRepaymentItemResultFieldIndex          = big.NewInt(1 << 0)
	bulkRepaymentItemResultFieldSuccess        = big.NewInt(1 << 1)
	bulkRepaymentItemResultFieldRepaymentLogID = big.NewInt(1 << 2)
	bulkRepaymentItemResultFieldError          = big.NewInt(1 << 3)
	bulkRepaymentItemResultFieldInstallmentID  = big.NewInt(1 << 4)
	bulkRepaymentItemResultFieldLoanID         = big.NewInt(1 << 5)
	bulkRepaymentItemResultFieldAmount         = big.NewInt(1 << 6)
)

type BulkRepaymentItemResult struct {
	// Index of the repayment in the original request
	Index int `json:"index" url:"index"`
	// Whether the repayment was processed successfully
	Success bool `json:"success" url:"success"`
	// ID of the created repayment log if successful
	RepaymentLogID *string `json:"repayment_log_id,omitempty" url:"repayment_log_id,omitempty"`
	// Error message if processing failed
	Error *string `json:"error,omitempty" url:"error,omitempty"`
	// ID of the associated installment
	InstallmentID *string `json:"installment_id,omitempty" url:"installment_id,omitempty"`
	// ID of the associated loan
	LoanID *string `json:"loan_id,omitempty" url:"loan_id,omitempty"`
	// Amount of the repayment
	Amount *string `json:"amount,omitempty" url:"amount,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BulkRepaymentItemResult) GetIndex() int {
	if b == nil {
		return 0
	}
	return b.Index
}

func (b *BulkRepaymentItemResult) GetSuccess() bool {
	if b == nil {
		return false
	}
	return b.Success
}

func (b *BulkRepaymentItemResult) GetRepaymentLogID() *string {
	if b == nil {
		return nil
	}
	return b.RepaymentLogID
}

func (b *BulkRepaymentItemResult) GetError() *string {
	if b == nil {
		return nil
	}
	return b.Error
}

func (b *BulkRepaymentItemResult) GetInstallmentID() *string {
	if b == nil {
		return nil
	}
	return b.InstallmentID
}

func (b *BulkRepaymentItemResult) GetLoanID() *string {
	if b == nil {
		return nil
	}
	return b.LoanID
}

func (b *BulkRepaymentItemResult) GetAmount() *string {
	if b == nil {
		return nil
	}
	return b.Amount
}

func (b *BulkRepaymentItemResult) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BulkRepaymentItemResult) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetIndex sets the Index field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemResult) SetIndex(index int) {
	b.Index = index
	b.require(bulkRepaymentItemResultFieldIndex)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemResult) SetSuccess(success bool) {
	b.Success = success
	b.require(bulkRepaymentItemResultFieldSuccess)
}

// SetRepaymentLogID sets the RepaymentLogID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemResult) SetRepaymentLogID(repaymentLogID *string) {
	b.RepaymentLogID = repaymentLogID
	b.require(bulkRepaymentItemResultFieldRepaymentLogID)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemResult) SetError(error_ *string) {
	b.Error = error_
	b.require(bulkRepaymentItemResultFieldError)
}

// SetInstallmentID sets the InstallmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemResult) SetInstallmentID(installmentID *string) {
	b.InstallmentID = installmentID
	b.require(bulkRepaymentItemResultFieldInstallmentID)
}

// SetLoanID sets the LoanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemResult) SetLoanID(loanID *string) {
	b.LoanID = loanID
	b.require(bulkRepaymentItemResultFieldLoanID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentItemResult) SetAmount(amount *string) {
	b.Amount = amount
	b.require(bulkRepaymentItemResultFieldAmount)
}

func (b *BulkRepaymentItemResult) UnmarshalJSON(data []byte) error {
	type unmarshaler BulkRepaymentItemResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BulkRepaymentItemResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BulkRepaymentItemResult) MarshalJSON() ([]byte, error) {
	type embed BulkRepaymentItemResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BulkRepaymentItemResult) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	bulkRepaymentResultFieldSuccessCount          = big.NewInt(1 << 0)
	bulkRepaymentResultFieldFailureCount          = big.NewInt(1 << 1)
	bulkRepaymentResultFieldTotalProcessed        = big.NewInt(1 << 2)
	bulkRepaymentResultFieldProcessingTimeSeconds = big.NewInt(1 << 3)
	bulkRepaymentResultFieldResults               = big.NewInt(1 << 4)
)

type BulkRepaymentResult struct {
	// Number of successfully processed repayments
	SuccessCount int `json:"success_count" url:"success_count"`
	// Number of failed repayments
	FailureCount int `json:"failure_count" url:"failure_count"`
	// Total number of repayments processed
	TotalProcessed int `json:"total_processed" url:"total_processed"`
	// Time taken to process all repayments
	ProcessingTimeSeconds float64 `json:"processing_time_seconds" url:"processing_time_seconds"`
	// Detailed results for each repayment
	Results []*BulkRepaymentItemResult `json:"results" url:"results"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BulkRepaymentResult) GetSuccessCount() int {
	if b == nil {
		return 0
	}
	return b.SuccessCount
}

func (b *BulkRepaymentResult) GetFailureCount() int {
	if b == nil {
		return 0
	}
	return b.FailureCount
}

func (b *BulkRepaymentResult) GetTotalProcessed() int {
	if b == nil {
		return 0
	}
	return b.TotalProcessed
}

func (b *BulkRepaymentResult) GetProcessingTimeSeconds() float64 {
	if b == nil {
		return 0
	}
	return b.ProcessingTimeSeconds
}

func (b *BulkRepaymentResult) GetResults() []*BulkRepaymentItemResult {
	if b == nil {
		return nil
	}
	return b.Results
}

func (b *BulkRepaymentResult) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BulkRepaymentResult) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetSuccessCount sets the SuccessCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentResult) SetSuccessCount(successCount int) {
	b.SuccessCount = successCount
	b.require(bulkRepaymentResultFieldSuccessCount)
}

// SetFailureCount sets the FailureCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentResult) SetFailureCount(failureCount int) {
	b.FailureCount = failureCount
	b.require(bulkRepaymentResultFieldFailureCount)
}

// SetTotalProcessed sets the TotalProcessed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentResult) SetTotalProcessed(totalProcessed int) {
	b.TotalProcessed = totalProcessed
	b.require(bulkRepaymentResultFieldTotalProcessed)
}

// SetProcessingTimeSeconds sets the ProcessingTimeSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentResult) SetProcessingTimeSeconds(processingTimeSeconds float64) {
	b.ProcessingTimeSeconds = processingTimeSeconds
	b.require(bulkRepaymentResultFieldProcessingTimeSeconds)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentResult) SetResults(results []*BulkRepaymentItemResult) {
	b.Results = results
	b.require(bulkRepaymentResultFieldResults)
}

func (b *BulkRepaymentResult) UnmarshalJSON(data []byte) error {
	type unmarshaler BulkRepaymentResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BulkRepaymentResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BulkRepaymentResult) MarshalJSON() ([]byte, error) {
	type embed BulkRepaymentResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BulkRepaymentResult) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	bulkRepaymentTaskResponseFieldTaskID                  = big.NewInt(1 << 0)
	bulkRepaymentTaskResponseFieldTotalRepayments         = big.NewInt(1 << 1)
	bulkRepaymentTaskResponseFieldEstimatedCompletionTime = big.NewInt(1 << 2)
)

type BulkRepaymentTaskResponse struct {
	// Task ID for tracking progress
	TaskID string `json:"task_id" url:"task_id"`
	// Number of repayments to process
	TotalRepayments int `json:"total_repayments" url:"total_repayments"`
	// Estimated completion time
	EstimatedCompletionTime string `json:"estimated_completion_time" url:"estimated_completion_time"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BulkRepaymentTaskResponse) GetTaskID() string {
	if b == nil {
		return ""
	}
	return b.TaskID
}

func (b *BulkRepaymentTaskResponse) GetTotalRepayments() int {
	if b == nil {
		return 0
	}
	return b.TotalRepayments
}

func (b *BulkRepaymentTaskResponse) GetEstimatedCompletionTime() string {
	if b == nil {
		return ""
	}
	return b.EstimatedCompletionTime
}

func (b *BulkRepaymentTaskResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BulkRepaymentTaskResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetTaskID sets the TaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentTaskResponse) SetTaskID(taskID string) {
	b.TaskID = taskID
	b.require(bulkRepaymentTaskResponseFieldTaskID)
}

// SetTotalRepayments sets the TotalRepayments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentTaskResponse) SetTotalRepayments(totalRepayments int) {
	b.TotalRepayments = totalRepayments
	b.require(bulkRepaymentTaskResponseFieldTotalRepayments)
}

// SetEstimatedCompletionTime sets the EstimatedCompletionTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentTaskResponse) SetEstimatedCompletionTime(estimatedCompletionTime string) {
	b.EstimatedCompletionTime = estimatedCompletionTime
	b.require(bulkRepaymentTaskResponseFieldEstimatedCompletionTime)
}

func (b *BulkRepaymentTaskResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler BulkRepaymentTaskResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BulkRepaymentTaskResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BulkRepaymentTaskResponse) MarshalJSON() ([]byte, error) {
	type embed BulkRepaymentTaskResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BulkRepaymentTaskResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	bulkRepaymentTaskStatusFieldTaskID  = big.NewInt(1 << 0)
	bulkRepaymentTaskStatusFieldStatus  = big.NewInt(1 << 1)
	bulkRepaymentTaskStatusFieldCurrent = big.NewInt(1 << 2)
	bulkRepaymentTaskStatusFieldTotal   = big.NewInt(1 << 3)
	bulkRepaymentTaskStatusFieldResult  = big.NewInt(1 << 4)
	bulkRepaymentTaskStatusFieldError   = big.NewInt(1 << 5)
)

type BulkRepaymentTaskStatus struct {
	// Task ID
	TaskID string `json:"task_id" url:"task_id"`
	// Task status
	Status string `json:"status" url:"status"`
	// Current progress count
	Current *int `json:"current,omitempty" url:"current,omitempty"`
	// Total items to process
	Total *int `json:"total,omitempty" url:"total,omitempty"`
	// Final result when task is completed
	Result *BulkRepaymentResult `json:"result,omitempty" url:"result,omitempty"`
	// Error message if task failed
	Error *string `json:"error,omitempty" url:"error,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BulkRepaymentTaskStatus) GetTaskID() string {
	if b == nil {
		return ""
	}
	return b.TaskID
}

func (b *BulkRepaymentTaskStatus) GetStatus() string {
	if b == nil {
		return ""
	}
	return b.Status
}

func (b *BulkRepaymentTaskStatus) GetCurrent() *int {
	if b == nil {
		return nil
	}
	return b.Current
}

func (b *BulkRepaymentTaskStatus) GetTotal() *int {
	if b == nil {
		return nil
	}
	return b.Total
}

func (b *BulkRepaymentTaskStatus) GetResult() *BulkRepaymentResult {
	if b == nil {
		return nil
	}
	return b.Result
}

func (b *BulkRepaymentTaskStatus) GetError() *string {
	if b == nil {
		return nil
	}
	return b.Error
}

func (b *BulkRepaymentTaskStatus) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BulkRepaymentTaskStatus) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetTaskID sets the TaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentTaskStatus) SetTaskID(taskID string) {
	b.TaskID = taskID
	b.require(bulkRepaymentTaskStatusFieldTaskID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentTaskStatus) SetStatus(status string) {
	b.Status = status
	b.require(bulkRepaymentTaskStatusFieldStatus)
}

// SetCurrent sets the Current field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentTaskStatus) SetCurrent(current *int) {
	b.Current = current
	b.require(bulkRepaymentTaskStatusFieldCurrent)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentTaskStatus) SetTotal(total *int) {
	b.Total = total
	b.require(bulkRepaymentTaskStatusFieldTotal)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentTaskStatus) SetResult(result *BulkRepaymentResult) {
	b.Result = result
	b.require(bulkRepaymentTaskStatusFieldResult)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BulkRepaymentTaskStatus) SetError(error_ *string) {
	b.Error = error_
	b.require(bulkRepaymentTaskStatusFieldError)
}

func (b *BulkRepaymentTaskStatus) UnmarshalJSON(data []byte) error {
	type unmarshaler BulkRepaymentTaskStatus
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BulkRepaymentTaskStatus(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BulkRepaymentTaskStatus) MarshalJSON() ([]byte, error) {
	type embed BulkRepaymentTaskStatus
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BulkRepaymentTaskStatus) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	repaymentResponseFieldID                = big.NewInt(1 << 0)
	repaymentResponseFieldCreatedAt         = big.NewInt(1 << 1)
	repaymentResponseFieldClientID          = big.NewInt(1 << 2)
	repaymentResponseFieldLoanID            = big.NewInt(1 << 3)
	repaymentResponseFieldInstallmentID     = big.NewInt(1 << 4)
	repaymentResponseFieldAmount            = big.NewInt(1 << 5)
	repaymentResponseFieldRepaymentDate     = big.NewInt(1 << 6)
	repaymentResponseFieldType              = big.NewInt(1 << 7)
	repaymentResponseFieldData              = big.NewInt(1 << 8)
	repaymentResponseFieldIsEarlySettlement = big.NewInt(1 << 9)
	repaymentResponseFieldPrincipalAmount   = big.NewInt(1 << 10)
	repaymentResponseFieldInterestAmount    = big.NewInt(1 << 11)
	repaymentResponseFieldLateFeeAmount     = big.NewInt(1 << 12)
)

type RepaymentResponse struct {
	// The ID of the repayment log
	ID string `json:"id" url:"id"`
	// The creation date of the repayment log
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// The ID of the client who made the payment
	ClientID string `json:"client_id" url:"client_id"`
	// The ID of the loan for which the payment was made
	LoanID string `json:"loan_id" url:"loan_id"`
	// The ID of the installment for which the payment was made
	InstallmentID string `json:"installment_id" url:"installment_id"`
	// The amount of payment made for installment
	Amount string `json:"amount" url:"amount"`
	// The date of the payment made for installment
	RepaymentDate *time.Time `json:"repayment_date,omitempty" url:"repayment_date,omitempty"`
	// The type of repayment sent in data field
	Type *string `json:"type,omitempty" url:"type,omitempty"`
	// Additional metadata related to the repayment
	Data map[string]any `json:"data,omitempty" url:"data,omitempty"`
	// Indicates if this repayment is for early settlement
	IsEarlySettlement *bool `json:"is_early_settlement,omitempty" url:"is_early_settlement,omitempty"`
	// Principal portion of the repayment, when the partner provides a breakdown of the payment components
	PrincipalAmount *string `json:"principal_amount,omitempty" url:"principal_amount,omitempty"`
	// Interest portion of the repayment, when the partner provides a breakdown of the payment components
	InterestAmount *string `json:"interest_amount,omitempty" url:"interest_amount,omitempty"`
	// Late fee portion of the repayment, when the partner provides a breakdown of the payment components
	LateFeeAmount *string `json:"late_fee_amount,omitempty" url:"late_fee_amount,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RepaymentResponse) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RepaymentResponse) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *RepaymentResponse) GetClientID() string {
	if r == nil {
		return ""
	}
	return r.ClientID
}

func (r *RepaymentResponse) GetLoanID() string {
	if r == nil {
		return ""
	}
	return r.LoanID
}

func (r *RepaymentResponse) GetInstallmentID() string {
	if r == nil {
		return ""
	}
	return r.InstallmentID
}

func (r *RepaymentResponse) GetAmount() string {
	if r == nil {
		return ""
	}
	return r.Amount
}

func (r *RepaymentResponse) GetRepaymentDate() *time.Time {
	if r == nil {
		return nil
	}
	return r.RepaymentDate
}

func (r *RepaymentResponse) GetType() *string {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *RepaymentResponse) GetData() map[string]any {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *RepaymentResponse) GetIsEarlySettlement() *bool {
	if r == nil {
		return nil
	}
	return r.IsEarlySettlement
}

func (r *RepaymentResponse) GetPrincipalAmount() *string {
	if r == nil {
		return nil
	}
	return r.PrincipalAmount
}

func (r *RepaymentResponse) GetInterestAmount() *string {
	if r == nil {
		return nil
	}
	return r.InterestAmount
}

func (r *RepaymentResponse) GetLateFeeAmount() *string {
	if r == nil {
		return nil
	}
	return r.LateFeeAmount
}

func (r *RepaymentResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RepaymentResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetID(id string) {
	r.ID = id
	r.require(repaymentResponseFieldID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetCreatedAt(createdAt time.Time) {
	r.CreatedAt = createdAt
	r.require(repaymentResponseFieldCreatedAt)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetClientID(clientID string) {
	r.ClientID = clientID
	r.require(repaymentResponseFieldClientID)
}

// SetLoanID sets the LoanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetLoanID(loanID string) {
	r.LoanID = loanID
	r.require(repaymentResponseFieldLoanID)
}

// SetInstallmentID sets the InstallmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetInstallmentID(installmentID string) {
	r.InstallmentID = installmentID
	r.require(repaymentResponseFieldInstallmentID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetAmount(amount string) {
	r.Amount = amount
	r.require(repaymentResponseFieldAmount)
}

// SetRepaymentDate sets the RepaymentDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetRepaymentDate(repaymentDate *time.Time) {
	r.RepaymentDate = repaymentDate
	r.require(repaymentResponseFieldRepaymentDate)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetType(type_ *string) {
	r.Type = type_
	r.require(repaymentResponseFieldType)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetData(data map[string]any) {
	r.Data = data
	r.require(repaymentResponseFieldData)
}

// SetIsEarlySettlement sets the IsEarlySettlement field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetIsEarlySettlement(isEarlySettlement *bool) {
	r.IsEarlySettlement = isEarlySettlement
	r.require(repaymentResponseFieldIsEarlySettlement)
}

// SetPrincipalAmount sets the PrincipalAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetPrincipalAmount(principalAmount *string) {
	r.PrincipalAmount = principalAmount
	r.require(repaymentResponseFieldPrincipalAmount)
}

// SetInterestAmount sets the InterestAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetInterestAmount(interestAmount *string) {
	r.InterestAmount = interestAmount
	r.require(repaymentResponseFieldInterestAmount)
}

// SetLateFeeAmount sets the LateFeeAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepaymentResponse) SetLateFeeAmount(lateFeeAmount *string) {
	r.LateFeeAmount = lateFeeAmount
	r.require(repaymentResponseFieldLateFeeAmount)
}

func (r *RepaymentResponse) UnmarshalJSON(data []byte) error {
	type embed RepaymentResponse
	var unmarshaler = struct {
		embed
		CreatedAt     *internal.DateTime `json:"created_at"`
		RepaymentDate *internal.DateTime `json:"repayment_date,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RepaymentResponse(unmarshaler.embed)
	r.CreatedAt = unmarshaler.CreatedAt.Time()
	r.RepaymentDate = unmarshaler.RepaymentDate.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RepaymentResponse) MarshalJSON() ([]byte, error) {
	type embed RepaymentResponse
	var marshaler = struct {
		embed
		CreatedAt     *internal.DateTime `json:"created_at"`
		RepaymentDate *internal.DateTime `json:"repayment_date,omitempty"`
	}{
		embed:         embed(*r),
		CreatedAt:     internal.NewDateTime(r.CreatedAt),
		RepaymentDate: internal.NewOptionalDateTime(r.RepaymentDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RepaymentResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// The amount of payment made for installment
type RepaymentCreatePayloadAmount struct {
	Double float64
	String string

	typ string
}

func (r *RepaymentCreatePayloadAmount) GetDouble() float64 {
	if r == nil {
		return 0
	}
	return r.Double
}

func (r *RepaymentCreatePayloadAmount) GetString() string {
	if r == nil {
		return ""
	}
	return r.String
}

func (r *RepaymentCreatePayloadAmount) UnmarshalJSON(data []byte) error {
	var valueDouble float64
	if err := json.Unmarshal(data, &valueDouble); err == nil {
		r.typ = "Double"
		r.Double = valueDouble
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		r.typ = "String"
		r.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, r)
}

func (r RepaymentCreatePayloadAmount) MarshalJSON() ([]byte, error) {
	if r.typ == "Double" || r.Double != 0 {
		return json.Marshal(r.Double)
	}
	if r.typ == "String" || r.String != "" {
		return json.Marshal(r.String)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", r)
}

type RepaymentCreatePayloadAmountVisitor interface {
	VisitDouble(float64) error
	VisitString(string) error
}

func (r *RepaymentCreatePayloadAmount) Accept(visitor RepaymentCreatePayloadAmountVisitor) error {
	if r.typ == "Double" || r.Double != 0 {
		return visitor.VisitDouble(r.Double)
	}
	if r.typ == "String" || r.String != "" {
		return visitor.VisitString(r.String)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", r)
}
