// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	big "math/big"
	time "time"
)

var (
	webhookCreatePayloadFieldURL         = big.NewInt(1 << 0)
	webhookCreatePayloadFieldDescription = big.NewInt(1 << 1)
	webhookCreatePayloadFieldEventType   = big.NewInt(1 << 2)
	webhookCreatePayloadFieldSecret      = big.NewInt(1 << 3)
	webhookCreatePayloadFieldRetry       = big.NewInt(1 << 4)
	webhookCreatePayloadFieldStatus      = big.NewInt(1 << 5)
)

type WebhookCreatePayload struct {
	// The URL to send webhooks to
	URL string `json:"url" url:"-"`
	// Optional description of this webhook endpoint
	Description *string `json:"description,omitempty" url:"-"`
	// Event type to subscribe toPossible values: loan_updated, installment_updated, client_updated, client_limit_updated, partner_limit_updated
	EventType WebhookEventTypeEnum `json:"event_type" url:"-"`
	// Secret for signing webhook payloads
	Secret string `json:"secret" url:"-"`
	// Whether to retry failed webhooks
	Retry *bool `json:"retry,omitempty" url:"-"`
	// Status of the webhook subscription. Defaults to 'active'.Possible values: active, paused, disabled
	Status *WebhookStatusEnum `json:"status,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WebhookCreatePayload) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookCreatePayload) SetURL(url string) {
	w.URL = url
	w.require(webhookCreatePayloadFieldURL)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookCreatePayload) SetDescription(description *string) {
	w.Description = description
	w.require(webhookCreatePayloadFieldDescription)
}

// SetEventType sets the EventType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookCreatePayload) SetEventType(eventType WebhookEventTypeEnum) {
	w.EventType = eventType
	w.require(webhookCreatePayloadFieldEventType)
}

// SetSecret sets the Secret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookCreatePayload) SetSecret(secret string) {
	w.Secret = secret
	w.require(webhookCreatePayloadFieldSecret)
}

// SetRetry sets the Retry field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookCreatePayload) SetRetry(retry *bool) {
	w.Retry = retry
	w.require(webhookCreatePayloadFieldRetry)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookCreatePayload) SetStatus(status *WebhookStatusEnum) {
	w.Status = status
	w.require(webhookCreatePayloadFieldStatus)
}

func (w *WebhookCreatePayload) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookCreatePayload
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*w = WebhookCreatePayload(body)
	return nil
}

func (w *WebhookCreatePayload) MarshalJSON() ([]byte, error) {
	type embed WebhookCreatePayload
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteWebhookSubscriptionRequestFieldWebhookID = big.NewInt(1 << 0)
)

type DeleteWebhookSubscriptionRequest struct {
	WebhookID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteWebhookSubscriptionRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetWebhookID sets the WebhookID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteWebhookSubscriptionRequest) SetWebhookID(webhookID string) {
	d.WebhookID = webhookID
	d.require(deleteWebhookSubscriptionRequestFieldWebhookID)
}

var (
	getWebhookSubscriptionRequestFieldWebhookID = big.NewInt(1 << 0)
)

type GetWebhookSubscriptionRequest struct {
	WebhookID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetWebhookSubscriptionRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetWebhookID sets the WebhookID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWebhookSubscriptionRequest) SetWebhookID(webhookID string) {
	g.WebhookID = webhookID
	g.require(getWebhookSubscriptionRequestFieldWebhookID)
}

var (
	listWebhookLogsRequestFieldWebhookID = big.NewInt(1 << 0)
	listWebhookLogsRequestFieldPage      = big.NewInt(1 << 1)
	listWebhookLogsRequestFieldPageSize  = big.NewInt(1 << 2)
)

type ListWebhookLogsRequest struct {
	WebhookID *string `json:"-" url:"webhook_id,omitempty"`
	Page      *int    `json:"-" url:"page,omitempty"`
	PageSize  *int    `json:"-" url:"page_size,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListWebhookLogsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetWebhookID sets the WebhookID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListWebhookLogsRequest) SetWebhookID(webhookID *string) {
	l.WebhookID = webhookID
	l.require(listWebhookLogsRequestFieldWebhookID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListWebhookLogsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listWebhookLogsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListWebhookLogsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listWebhookLogsRequestFieldPageSize)
}

var (
	listWebhookSubscriptionsRequestFieldPage      = big.NewInt(1 << 0)
	listWebhookSubscriptionsRequestFieldPageSize  = big.NewInt(1 << 1)
	listWebhookSubscriptionsRequestFieldEventType = big.NewInt(1 << 2)
)

type ListWebhookSubscriptionsRequest struct {
	Page      *int                  `json:"-" url:"page,omitempty"`
	PageSize  *int                  `json:"-" url:"page_size,omitempty"`
	EventType *WebhookEventTypeEnum `json:"-" url:"event_type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListWebhookSubscriptionsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListWebhookSubscriptionsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listWebhookSubscriptionsRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListWebhookSubscriptionsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listWebhookSubscriptionsRequestFieldPageSize)
}

// SetEventType sets the EventType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListWebhookSubscriptionsRequest) SetEventType(eventType *WebhookEventTypeEnum) {
	l.EventType = eventType
	l.require(listWebhookSubscriptionsRequestFieldEventType)
}

var (
	paginatedResponseWebhookLogResponseFieldItems       = big.NewInt(1 << 0)
	paginatedResponseWebhookLogResponseFieldPage        = big.NewInt(1 << 1)
	paginatedResponseWebhookLogResponseFieldPageSize    = big.NewInt(1 << 2)
	paginatedResponseWebhookLogResponseFieldItemsInPage = big.NewInt(1 << 3)
	paginatedResponseWebhookLogResponseFieldTotalItems  = big.NewInt(1 << 4)
	paginatedResponseWebhookLogResponseFieldTotalPages  = big.NewInt(1 << 5)
	paginatedResponseWebhookLogResponseFieldHasNext     = big.NewInt(1 << 6)
	paginatedResponseWebhookLogResponseFieldHasPrevious = big.NewInt(1 << 7)
)

type PaginatedResponseWebhookLogResponse struct {
	Items []*WebhookLogResponse `json:"items" url:"items"`
	// Current page number
	Page *int `json:"page,omitempty" url:"page,omitempty"`
	// Number of items per page
	PageSize *int `json:"page_size,omitempty" url:"page_size,omitempty"`
	// Number of items in the current page
	ItemsInPage *int `json:"items_in_page,omitempty" url:"items_in_page,omitempty"`
	// Total number of items across all pages
	TotalItems *int `json:"total_items,omitempty" url:"total_items,omitempty"`
	// Total number of pages available
	TotalPages *int `json:"total_pages,omitempty" url:"total_pages,omitempty"`
	// Indicates if there is a next page
	HasNext *bool `json:"has_next,omitempty" url:"has_next,omitempty"`
	// Indicates if there is a previous page
	HasPrevious *bool `json:"has_previous,omitempty" url:"has_previous,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginatedResponseWebhookLogResponse) GetItems() []*WebhookLogResponse {
	if p == nil {
		return nil
	}
	return p.Items
}

func (p *PaginatedResponseWebhookLogResponse) GetPage() *int {
	if p == nil {
		return nil
	}
	return p.Page
}

func (p *PaginatedResponseWebhookLogResponse) GetPageSize() *int {
	if p == nil {
		return nil
	}
	return p.PageSize
}

func (p *PaginatedResponseWebhookLogResponse) GetItemsInPage() *int {
	if p == nil {
		return nil
	}
	return p.ItemsInPage
}

func (p *PaginatedResponseWebhookLogResponse) GetTotalItems() *int {
	if p == nil {
		return nil
	}
	return p.TotalItems
}

func (p *PaginatedResponseWebhookLogResponse) GetTotalPages() *int {
	if p == nil {
		return nil
	}
	return p.TotalPages
}

func (p *PaginatedResponseWebhookLogResponse) GetHasNext() *bool {
	if p == nil {
		return nil
	}
	return p.HasNext
}

func (p *PaginatedResponseWebhookLogResponse) GetHasPrevious() *bool {
	if p == nil {
		return nil
	}
	return p.HasPrevious
}

func (p *PaginatedResponseWebhookLogResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PaginatedResponseWebhookLogResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookLogResponse) SetItems(items []*WebhookLogResponse) {
	p.Items = items
	p.require(paginatedResponseWebhookLogResponseFieldItems)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookLogResponse) SetPage(page *int) {
	p.Page = page
	p.require(paginatedResponseWebhookLogResponseFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookLogResponse) SetPageSize(pageSize *int) {
	p.PageSize = pageSize
	p.require(paginatedResponseWebhookLogResponseFieldPageSize)
}

// SetItemsInPage sets the ItemsInPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookLogResponse) SetItemsInPage(itemsInPage *int) {
	p.ItemsInPage = itemsInPage
	p.require(paginatedResponseWebhookLogResponseFieldItemsInPage)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookLogResponse) SetTotalItems(totalItems *int) {
	p.TotalItems = totalItems
	p.require(paginatedResponseWebhookLogResponseFieldTotalItems)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookLogResponse) SetTotalPages(totalPages *int) {
	p.TotalPages = totalPages
	p.require(paginatedResponseWebhookLogResponseFieldTotalPages)
}

// SetHasNext sets the HasNext field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookLogResponse) SetHasNext(hasNext *bool) {
	p.HasNext = hasNext
	p.require(paginatedResponseWebhookLogResponseFieldHasNext)
}

// SetHasPrevious sets the HasPrevious field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookLogResponse) SetHasPrevious(hasPrevious *bool) {
	p.HasPrevious = hasPrevious
	p.require(paginatedResponseWebhookLogResponseFieldHasPrevious)
}

func (p *PaginatedResponseWebhookLogResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedResponseWebhookLogResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedResponseWebhookLogResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedResponseWebhookLogResponse) MarshalJSON() ([]byte, error) {
	type embed PaginatedResponseWebhookLogResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginatedResponseWebhookLogResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	paginatedResponseWebhookSubscriptionResponseFieldItems       = big.NewInt(1 << 0)
	paginatedResponseWebhookSubscriptionResponseFieldPage        = big.NewInt(1 << 1)
	paginatedResponseWebhookSubscriptionResponseFieldPageSize    = big.NewInt(1 << 2)
	paginatedResponseWebhookSubscriptionResponseFieldItemsInPage = big.NewInt(1 << 3)
	paginatedResponseWebhookSubscriptionResponseFieldTotalItems  = big.NewInt(1 << 4)
	paginatedResponseWebhookSubscriptionResponseFieldTotalPages  = big.NewInt(1 << 5)
	paginatedResponseWebhookSubscriptionResponseFieldHasNext     = big.NewInt(1 << 6)
	paginatedResponseWebhookSubscriptionResponseFieldHasPrevious = big.NewInt(1 << 7)
)

type PaginatedResponseWebhookSubscriptionResponse struct {
	Items []*WebhookSubscriptionResponse `json:"items" url:"items"`
	// Current page number
	Page *int `json:"page,omitempty" url:"page,omitempty"`
	// Number of items per page
	PageSize *int `json:"page_size,omitempty" url:"page_size,omitempty"`
	// Number of items in the current page
	ItemsInPage *int `json:"items_in_page,omitempty" url:"items_in_page,omitempty"`
	// Total number of items across all pages
	TotalItems *int `json:"total_items,omitempty" url:"total_items,omitempty"`
	// Total number of pages available
	TotalPages *int `json:"total_pages,omitempty" url:"total_pages,omitempty"`
	// Indicates if there is a next page
	HasNext *bool `json:"has_next,omitempty" url:"has_next,omitempty"`
	// Indicates if there is a previous page
	HasPrevious *bool `json:"has_previous,omitempty" url:"has_previous,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginatedResponseWebhookSubscriptionResponse) GetItems() []*WebhookSubscriptionResponse {
	if p == nil {
		return nil
	}
	return p.Items
}

func (p *PaginatedResponseWebhookSubscriptionResponse) GetPage() *int {
	if p == nil {
		return nil
	}
	return p.Page
}

func (p *PaginatedResponseWebhookSubscriptionResponse) GetPageSize() *int {
	if p == nil {
		return nil
	}
	return p.PageSize
}

func (p *PaginatedResponseWebhookSubscriptionResponse) GetItemsInPage() *int {
	if p == nil {
		return nil
	}
	return p.ItemsInPage
}

func (p *PaginatedResponseWebhookSubscriptionResponse) GetTotalItems() *int {
	if p == nil {
		return nil
	}
	return p.TotalItems
}

func (p *PaginatedResponseWebhookSubscriptionResponse) GetTotalPages() *int {
	if p == nil {
		return nil
	}
	return p.TotalPages
}

func (p *PaginatedResponseWebhookSubscriptionResponse) GetHasNext() *bool {
	if p == nil {
		return nil
	}
	return p.HasNext
}

func (p *PaginatedResponseWebhookSubscriptionResponse) GetHasPrevious() *bool {
	if p == nil {
		return nil
	}
	return p.HasPrevious
}

func (p *PaginatedResponseWebhookSubscriptionResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PaginatedResponseWebhookSubscriptionResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookSubscriptionResponse) SetItems(items []*WebhookSubscriptionResponse) {
	p.Items = items
	p.require(paginatedResponseWebhookSubscriptionResponseFieldItems)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookSubscriptionResponse) SetPage(page *int) {
	p.Page = page
	p.require(paginatedResponseWebhookSubscriptionResponseFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookSubscriptionResponse) SetPageSize(pageSize *int) {
	p.PageSize = pageSize
	p.require(paginatedResponseWebhookSubscriptionResponseFieldPageSize)
}

// SetItemsInPage sets the ItemsInPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookSubscriptionResponse) SetItemsInPage(itemsInPage *int) {
	p.ItemsInPage = itemsInPage
	p.require(paginatedResponseWebhookSubscriptionResponseFieldItemsInPage)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookSubscriptionResponse) SetTotalItems(totalItems *int) {
	p.TotalItems = totalItems
	p.require(paginatedResponseWebhookSubscriptionResponseFieldTotalItems)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookSubscriptionResponse) SetTotalPages(totalPages *int) {
	p.TotalPages = totalPages
	p.require(paginatedResponseWebhookSubscriptionResponseFieldTotalPages)
}

// SetHasNext sets the HasNext field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookSubscriptionResponse) SetHasNext(hasNext *bool) {
	p.HasNext = hasNext
	p.require(paginatedResponseWebhookSubscriptionResponseFieldHasNext)
}

// SetHasPrevious sets the HasPrevious field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseWebhookSubscriptionResponse) SetHasPrevious(hasPrevious *bool) {
	p.HasPrevious = hasPrevious
	p.require(paginatedResponseWebhookSubscriptionResponseFieldHasPrevious)
}

func (p *PaginatedResponseWebhookSubscriptionResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedResponseWebhookSubscriptionResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedResponseWebhookSubscriptionResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedResponseWebhookSubscriptionResponse) MarshalJSON() ([]byte, error) {
	type embed PaginatedResponseWebhookSubscriptionResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginatedResponseWebhookSubscriptionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	webhookLogResponseFieldID                = big.NewInt(1 << 0)
	webhookLogResponseFieldWebhookID         = big.NewInt(1 << 1)
	webhookLogResponseFieldCreatedAt         = big.NewInt(1 << 2)
	webhookLogResponseFieldUpdatedAt         = big.NewInt(1 << 3)
	webhookLogResponseFieldEventType         = big.NewInt(1 << 4)
	webhookLogResponseFieldWebhookURL        = big.NewInt(1 << 5)
	webhookLogResponseFieldSuccess           = big.NewInt(1 << 6)
	webhookLogResponseFieldStatusCode        = big.NewInt(1 << 7)
	webhookLogResponseFieldErrorMessage      = big.NewInt(1 << 8)
	webhookLogResponseFieldRequestDurationMs = big.NewInt(1 << 9)
	webhookLogResponseFieldRequestBody       = big.NewInt(1 << 10)
)

type WebhookLogResponse struct {
	// The ID of the webhook log
	ID string `json:"id" url:"id"`
	// The ID of the webhook subscription
	WebhookID string `json:"webhook_id" url:"webhook_id"`
	// Creation timestamp
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`
	// The type of event
	EventType WebhookEventTypeEnum `json:"event_type" url:"event_type"`
	// The URL of the webhook subscription
	WebhookURL string `json:"webhook_url" url:"webhook_url"`
	// Whether the webhook was delivered successfully
	Success bool `json:"success" url:"success"`
	// The HTTP status code returned by the server
	StatusCode *int `json:"status_code,omitempty" url:"status_code,omitempty"`
	// Error message if the webhook failed
	ErrorMessage *string `json:"error_message,omitempty" url:"error_message,omitempty"`
	// The time taken to deliver the webhook in milliseconds
	RequestDurationMs *int `json:"request_duration_ms,omitempty" url:"request_duration_ms,omitempty"`
	// The request body sent to the webhook URL
	RequestBody *WebhookLogResponseRequestBody `json:"request_body,omitempty" url:"request_body,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookLogResponse) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WebhookLogResponse) GetWebhookID() string {
	if w == nil {
		return ""
	}
	return w.WebhookID
}

func (w *WebhookLogResponse) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *WebhookLogResponse) GetUpdatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.UpdatedAt
}

func (w *WebhookLogResponse) GetEventType() WebhookEventTypeEnum {
	if w == nil {
		return ""
	}
	return w.EventType
}

func (w *WebhookLogResponse) GetWebhookURL() string {
	if w == nil {
		return ""
	}
	return w.WebhookURL
}

func (w *WebhookLogResponse) GetSuccess() bool {
	if w == nil {
		return false
	}
	return w.Success
}

func (w *WebhookLogResponse) GetStatusCode() *int {
	if w == nil {
		return nil
	}
	return w.StatusCode
}

func (w *WebhookLogResponse) GetErrorMessage() *string {
	if w == nil {
		return nil
	}
	return w.ErrorMessage
}

func (w *WebhookLogResponse) GetRequestDurationMs() *int {
	if w == nil {
		return nil
	}
	return w.RequestDurationMs
}

func (w *WebhookLogResponse) GetRequestBody() *WebhookLogResponseRequestBody {
	if w == nil {
		return nil
	}
	return w.RequestBody
}

func (w *WebhookLogResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookLogResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookLogResponse) SetID(id string) {
	w.ID = id
	w.require(webhookLogResponseFieldID)
}

// SetWebhookID sets the WebhookID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookLogResponse) SetWebhookID(webhookID string) {
	w.WebhookID = webhookID
	w.require(webhookLogResponseFieldWebhookID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookLogResponse) SetCreatedAt(createdAt time.Time) {
	w.CreatedAt = createdAt
	w.require(webhookLogResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookLogResponse) SetUpdatedAt(updatedAt time.Time) {
	w.UpdatedAt = updatedAt
	w.require(webhookLogResponseFieldUpdatedAt)
}

// SetEventType sets the EventType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookLogResponse) SetEventType(eventType WebhookEventTypeEnum) {
	w.EventType = eventType
	w.require(webhookLogResponseFieldEventType)
}

// SetWebhookURL sets the WebhookURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookLogResponse) SetWebhookURL(webhookURL string) {
	w.WebhookURL = webhookURL
	w.require(webhookLogResponseFieldWebhookURL)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookLogResponse) SetSuccess(success bool) {
	w.Success = success
	w.require(webhookLogResponseFieldSuccess)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookLogResponse) SetStatusCode(statusCode *int) {
	w.StatusCode = statusCode
	w.require(webhookLogResponseFieldStatusCode)
}

// SetErrorMessage sets the ErrorMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookLogResponse) SetErrorMessage(errorMessage *string) {
	w.ErrorMessage = errorMessage
	w.require(webhookLogResponseFieldErrorMessage)
}

// SetRequestDurationMs sets the RequestDurationMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookLogResponse) SetRequestDurationMs(requestDurationMs *int) {
	w.RequestDurationMs = requestDurationMs
	w.require(webhookLogResponseFieldRequestDurationMs)
}

// SetRequestBody sets the RequestBody field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookLogResponse) SetRequestBody(requestBody *WebhookLogResponseRequestBody) {
	w.RequestBody = requestBody
	w.require(webhookLogResponseFieldRequestBody)
}

func (w *WebhookLogResponse) UnmarshalJSON(data []byte) error {
	type embed WebhookLogResponse
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WebhookLogResponse(unmarshaler.embed)
	w.CreatedAt = unmarshaler.CreatedAt.Time()
	w.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookLogResponse) MarshalJSON() ([]byte, error) {
	type embed WebhookLogResponse
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*w),
		CreatedAt: internal.NewDateTime(w.CreatedAt),
		UpdatedAt: internal.NewDateTime(w.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookLogResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// The request body sent to the webhook URL
type WebhookLogResponseRequestBody struct {
	StringUnknownMap map[string]any
	UnknownList      []any

	typ string
}

func (w *WebhookLogResponseRequestBody) GetStringUnknownMap() map[string]any {
	if w == nil {
		return nil
	}
	return w.StringUnknownMap
}

func (w *WebhookLogResponseRequestBody) GetUnknownList() []any {
	if w == nil {
		return nil
	}
	return w.UnknownList
}

func (w *WebhookLogResponseRequestBody) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMap map[string]any
	if err := json.Unmarshal(data, &valueStringUnknownMap); err == nil {
		w.typ = "StringUnknownMap"
		w.StringUnknownMap = valueStringUnknownMap
		return nil
	}
	var valueUnknownList []any
	if err := json.Unmarshal(data, &valueUnknownList); err == nil {
		w.typ = "UnknownList"
		w.UnknownList = valueUnknownList
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, w)
}

func (w WebhookLogResponseRequestBody) MarshalJSON() ([]byte, error) {
	if w.typ == "StringUnknownMap" || w.StringUnknownMap != nil {
		return json.Marshal(w.StringUnknownMap)
	}
	if w.typ == "UnknownList" || w.UnknownList != nil {
		return json.Marshal(w.UnknownList)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", w)
}

type WebhookLogResponseRequestBodyVisitor interface {
	VisitStringUnknownMap(map[string]any) error
	VisitUnknownList([]any) error
}

func (w *WebhookLogResponseRequestBody) Accept(visitor WebhookLogResponseRequestBodyVisitor) error {
	if w.typ == "StringUnknownMap" || w.StringUnknownMap != nil {
		return visitor.VisitStringUnknownMap(w.StringUnknownMap)
	}
	if w.typ == "UnknownList" || w.UnknownList != nil {
		return visitor.VisitUnknownList(w.UnknownList)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", w)
}

type WebhookStatusEnum string

const (
	WebhookStatusEnumActive   WebhookStatusEnum = "active"
	WebhookStatusEnumPaused   WebhookStatusEnum = "paused"
	WebhookStatusEnumDisabled WebhookStatusEnum = "disabled"
)

func NewWebhookStatusEnumFromString(s string) (WebhookStatusEnum, error) {
	switch s {
	case "active":
		return WebhookStatusEnumActive, nil
	case "paused":
		return WebhookStatusEnumPaused, nil
	case "disabled":
		return WebhookStatusEnumDisabled, nil
	}
	var t WebhookStatusEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WebhookStatusEnum) Ptr() *WebhookStatusEnum {
	return &w
}

var (
	webhookSubscriptionResponseFieldID          = big.NewInt(1 << 0)
	webhookSubscriptionResponseFieldURL         = big.NewInt(1 << 1)
	webhookSubscriptionResponseFieldDescription = big.NewInt(1 << 2)
	webhookSubscriptionResponseFieldEventType   = big.NewInt(1 << 3)
	webhookSubscriptionResponseFieldStatus      = big.NewInt(1 << 4)
	webhookSubscriptionResponseFieldRetry       = big.NewInt(1 << 5)
	webhookSubscriptionResponseFieldSecret      = big.NewInt(1 << 6)
	webhookSubscriptionResponseFieldCreatedAt   = big.NewInt(1 << 7)
	webhookSubscriptionResponseFieldUpdatedAt   = big.NewInt(1 << 8)
)

type WebhookSubscriptionResponse struct {
	// The ID of the webhook subscription
	ID string `json:"id" url:"id"`
	// The URL to send webhooks to
	URL string `json:"url" url:"url"`
	// Description of this webhook endpoint
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Event type subscribed toPossible values: loan_updated, installment_updated, client_updated, client_limit_updated, partner_limit_updated
	EventType WebhookEventTypeEnum `json:"event_type" url:"event_type"`
	// Status of the webhook subscriptionPossible values: active, paused, disabled
	Status WebhookStatusEnum `json:"status" url:"status"`
	// Whether to retry failed webhooks
	Retry bool `json:"retry" url:"retry"`
	// Secret for signing webhook payloads
	Secret string `json:"secret" url:"secret"`
	// Creation timestamp
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookSubscriptionResponse) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WebhookSubscriptionResponse) GetURL() string {
	if w == nil {
		return ""
	}
	return w.URL
}

func (w *WebhookSubscriptionResponse) GetDescription() *string {
	if w == nil {
		return nil
	}
	return w.Description
}

func (w *WebhookSubscriptionResponse) GetEventType() WebhookEventTypeEnum {
	if w == nil {
		return ""
	}
	return w.EventType
}

func (w *WebhookSubscriptionResponse) GetStatus() WebhookStatusEnum {
	if w == nil {
		return ""
	}
	return w.Status
}

func (w *WebhookSubscriptionResponse) GetRetry() bool {
	if w == nil {
		return false
	}
	return w.Retry
}

func (w *WebhookSubscriptionResponse) GetSecret() string {
	if w == nil {
		return ""
	}
	return w.Secret
}

func (w *WebhookSubscriptionResponse) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *WebhookSubscriptionResponse) GetUpdatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.UpdatedAt
}

func (w *WebhookSubscriptionResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookSubscriptionResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSubscriptionResponse) SetID(id string) {
	w.ID = id
	w.require(webhookSubscriptionResponseFieldID)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSubscriptionResponse) SetURL(url string) {
	w.URL = url
	w.require(webhookSubscriptionResponseFieldURL)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSubscriptionResponse) SetDescription(description *string) {
	w.Description = description
	w.require(webhookSubscriptionResponseFieldDescription)
}

// SetEventType sets the EventType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSubscriptionResponse) SetEventType(eventType WebhookEventTypeEnum) {
	w.EventType = eventType
	w.require(webhookSubscriptionResponseFieldEventType)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSubscriptionResponse) SetStatus(status WebhookStatusEnum) {
	w.Status = status
	w.require(webhookSubscriptionResponseFieldStatus)
}

// SetRetry sets the Retry field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSubscriptionResponse) SetRetry(retry bool) {
	w.Retry = retry
	w.require(webhookSubscriptionResponseFieldRetry)
}

// SetSecret sets the Secret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSubscriptionResponse) SetSecret(secret string) {
	w.Secret = secret
	w.require(webhookSubscriptionResponseFieldSecret)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSubscriptionResponse) SetCreatedAt(createdAt time.Time) {
	w.CreatedAt = createdAt
	w.require(webhookSubscriptionResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookSubscriptionResponse) SetUpdatedAt(updatedAt time.Time) {
	w.UpdatedAt = updatedAt
	w.require(webhookSubscriptionResponseFieldUpdatedAt)
}

func (w *WebhookSubscriptionResponse) UnmarshalJSON(data []byte) error {
	type embed WebhookSubscriptionResponse
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WebhookSubscriptionResponse(unmarshaler.embed)
	w.CreatedAt = unmarshaler.CreatedAt.Time()
	w.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookSubscriptionResponse) MarshalJSON() ([]byte, error) {
	type embed WebhookSubscriptionResponse
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*w),
		CreatedAt: internal.NewDateTime(w.CreatedAt),
		UpdatedAt: internal.NewDateTime(w.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookSubscriptionResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	webhookUpdatePayloadFieldWebhookID   = big.NewInt(1 << 0)
	webhookUpdatePayloadFieldURL         = big.NewInt(1 << 1)
	webhookUpdatePayloadFieldDescription = big.NewInt(1 << 2)
	webhookUpdatePayloadFieldEventType   = big.NewInt(1 << 3)
	webhookUpdatePayloadFieldStatus      = big.NewInt(1 << 4)
	webhookUpdatePayloadFieldRetry       = big.NewInt(1 << 5)
	webhookUpdatePayloadFieldSecret      = big.NewInt(1 << 6)
)

type WebhookUpdatePayload struct {
	WebhookID string `json:"-" url:"-"`
	// The URL to send webhooks to
	URL *string `json:"url,omitempty" url:"-"`
	// Description of this webhook endpoint
	Description *string `json:"description,omitempty" url:"-"`
	// Event type to subscribe toPossible values: loan_updated, installment_updated, client_updated, client_limit_updated, partner_limit_updated
	EventType *WebhookEventTypeEnum `json:"event_type,omitempty" url:"-"`
	// Status of the webhook subscriptionPossible values: active, paused, disabled
	Status *WebhookStatusEnum `json:"status,omitempty" url:"-"`
	// Whether to retry failed webhooks
	Retry *bool `json:"retry,omitempty" url:"-"`
	// Secret for signing webhook payloads
	Secret *string `json:"secret,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WebhookUpdatePayload) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetWebhookID sets the WebhookID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookUpdatePayload) SetWebhookID(webhookID string) {
	w.WebhookID = webhookID
	w.require(webhookUpdatePayloadFieldWebhookID)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookUpdatePayload) SetURL(url *string) {
	w.URL = url
	w.require(webhookUpdatePayloadFieldURL)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookUpdatePayload) SetDescription(description *string) {
	w.Description = description
	w.require(webhookUpdatePayloadFieldDescription)
}

// SetEventType sets the EventType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookUpdatePayload) SetEventType(eventType *WebhookEventTypeEnum) {
	w.EventType = eventType
	w.require(webhookUpdatePayloadFieldEventType)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookUpdatePayload) SetStatus(status *WebhookStatusEnum) {
	w.Status = status
	w.require(webhookUpdatePayloadFieldStatus)
}

// SetRetry sets the Retry field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookUpdatePayload) SetRetry(retry *bool) {
	w.Retry = retry
	w.require(webhookUpdatePayloadFieldRetry)
}

// SetSecret sets the Secret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookUpdatePayload) SetSecret(secret *string) {
	w.Secret = secret
	w.require(webhookUpdatePayloadFieldSecret)
}

func (w *WebhookUpdatePayload) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookUpdatePayload
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*w = WebhookUpdatePayload(body)
	return nil
}

func (w *WebhookUpdatePayload) MarshalJSON() ([]byte, error) {
	type embed WebhookUpdatePayload
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}
