// Code generated by Fern. DO NOT EDIT.

package clients_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	require "github.com/stretchr/testify/require"
	v2 "github.com/voltariafinance/go-sdk/v2"
	client "github.com/voltariafinance/go-sdk/v2/client"
	option "github.com/voltariafinance/go-sdk/v2/option"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestClientsListClientsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.ListClientsRequest{}
	_, invocationErr := client.Clients.ListClients(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsListClientsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsListClientsWithWireMock", "GET", "/v2/clients", nil, 1)
}

func TestClientsCreateClientWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.ClientCreatePayload{
		Name:         "ACME Corp",
		Jurisdiction: v2.JurisdictionEnumEu,
	}
	_, invocationErr := client.Clients.CreateClient(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsCreateClientWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsCreateClientWithWireMock", "POST", "/v2/clients", nil, 1)
}

func TestClientsCreateClientDataWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.ClientDataCreatePayload{
		ClientID: "client_123",
		Data: map[string]any{
			"key1": "value1",
			"key2": "value2",
		},
	}
	_, invocationErr := client.Clients.CreateClientData(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsCreateClientDataWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsCreateClientDataWithWireMock", "POST", "/v2/clients/data", nil, 1)
}

func TestClientsListLimitRequestsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.ListLimitRequestsRequest{}
	_, invocationErr := client.Clients.ListLimitRequests(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsListLimitRequestsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsListLimitRequestsWithWireMock", "GET", "/v2/clients/limit-requests", nil, 1)
}

func TestClientsCreateLimitRequestWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.LimitRequestCreatePayload{
		ClientID: "client_1234567890abcdef",
		RequestedLimit: &v2.LimitRequestCreatePayloadRequestedLimit{
			Double: 1.1,
		},
		Reason: "Need more credit for business expansion",
	}
	_, invocationErr := client.Clients.CreateLimitRequest(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsCreateLimitRequestWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsCreateLimitRequestWithWireMock", "POST", "/v2/clients/limit-requests", nil, 1)
}

func TestClientsGetLimitRequestWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.GetLimitRequestRequest{
		RequestID: "request_id",
	}
	_, invocationErr := client.Clients.GetLimitRequest(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsGetLimitRequestWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsGetLimitRequestWithWireMock", "GET", "/v2/clients/limit-requests/request_id", nil, 1)
}

func TestClientsListOnboardingClientsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.ListOnboardingClientsRequest{}
	_, invocationErr := client.Clients.ListOnboardingClients(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsListOnboardingClientsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsListOnboardingClientsWithWireMock", "GET", "/v2/clients/onboarding", nil, 1)
}

func TestClientsApproveOnboardingWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.ApproveOnboardingRequest{
		ClientID: "client_id",
	}
	_, invocationErr := client.Clients.ApproveOnboarding(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsApproveOnboardingWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsApproveOnboardingWithWireMock", "POST", "/v2/clients/onboarding/client_id/approve", nil, 1)
}

func TestClientsRejectOnboardingWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.RejectOnboardingRequest{
		ClientID: "client_id",
	}
	_, invocationErr := client.Clients.RejectOnboarding(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsRejectOnboardingWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsRejectOnboardingWithWireMock", "POST", "/v2/clients/onboarding/client_id/reject", nil, 1)
}

func TestClientsAddClientPortalUserWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.ClientUserInviteRequest{
		ClientID:  "client_id",
		FirstName: "first_name",
		LastName:  "last_name",
		Email:     "email",
		RoleType:  "role_type",
	}
	_, invocationErr := client.Clients.AddClientPortalUser(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsAddClientPortalUserWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsAddClientPortalUserWithWireMock", "POST", "/v2/clients/client_id/users", nil, 1)
}

func TestClientsListClientWaiversWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.ListClientWaiversRequest{
		ClientID: "client_id",
	}
	_, invocationErr := client.Clients.ListClientWaivers(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsListClientWaiversWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsListClientWaiversWithWireMock", "GET", "/v2/clients/client_id/waivers", nil, 1)
}

func TestClientsGetClientByIDWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.GetClientByIDRequest{
		ClientID: "client_id",
	}
	_, invocationErr := client.Clients.GetClientByID(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsGetClientByIDWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsGetClientByIDWithWireMock", "GET", "/v2/clients/client_id", nil, 1)
}

func TestClientsDeleteClientWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.DeleteClientRequest{
		ClientID: "client_id",
	}
	_, invocationErr := client.Clients.DeleteClient(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsDeleteClientWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsDeleteClientWithWireMock", "DELETE", "/v2/clients/client_id", nil, 1)
}

func TestClientsListClientChecklistSummariesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &v2.ListClientChecklistSummariesRequest{
		ClientID: "client_id",
	}
	_, invocationErr := client.Clients.ListClientChecklistSummaries(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestClientsListClientChecklistSummariesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestClientsListClientChecklistSummariesWithWireMock", "GET", "/v2/clients/client_id/checklist-summaries", nil, 1)
}
