// Code generated by Fern. DO NOT EDIT.

package tasks

import (
	context "context"

	v2 "github.com/voltariafinance/go-sdk/v2"
	core "github.com/voltariafinance/go-sdk/v2/core"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	option "github.com/voltariafinance/go-sdk/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Paginated list of the tasks shared with your partner account, optionally filtered by status or by the client, loan, installment or waterfall they relate to.
func (c *Client) ListTasks(
	ctx context.Context,
	request *v2.ListTasksRequest,
	opts ...option.RequestOption,
) (*v2.PaginatedResponseTaskPartnerResponse, error) {
	response, err := c.WithRawResponse.ListTasks(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Open a task for your partner account. Any entity you link to it must belong to you.
func (c *Client) CreateTask(
	ctx context.Context,
	request *v2.TaskPartnerCreatePayload,
	opts ...option.RequestOption,
) (*v2.TaskPartnerResponse, error) {
	response, err := c.WithRawResponse.CreateTask(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve one of your tasks by its ID.
func (c *Client) GetTask(
	ctx context.Context,
	request *v2.GetTaskRequest,
	opts ...option.RequestOption,
) (*v2.TaskPartnerResponse, error) {
	response, err := c.WithRawResponse.GetTask(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Move one of your tasks to another status. Status is the only field you can change. Requires a signed-in user — API keys cannot change a task.
func (c *Client) UpdateTaskStatus(
	ctx context.Context,
	request *v2.TaskPartnerStatusUpdatePayload,
	opts ...option.RequestOption,
) (*v2.TaskPartnerResponse, error) {
	response, err := c.WithRawResponse.UpdateTaskStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The status transitions of one of your tasks, and whether each one was made by your team or by Voltaria support.
func (c *Client) ListTaskStatusHistory(
	ctx context.Context,
	request *v2.ListTaskStatusHistoryRequest,
	opts ...option.RequestOption,
) (*v2.PaginatedResponseTaskPartnerStatusHistoryResponse, error) {
	response, err := c.WithRawResponse.ListTaskStatusHistory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Notes exchanged with Voltaria on one of your tasks.
func (c *Client) ListTaskNotes(
	ctx context.Context,
	request *v2.ListTaskNotesRequest,
	opts ...option.RequestOption,
) (*v2.PaginatedResponseNoteResponse, error) {
	response, err := c.WithRawResponse.ListTaskNotes(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Add a note to one of your tasks. Requires a signed-in user — API keys cannot write notes, because a note needs an author.
func (c *Client) CreateTaskNote(
	ctx context.Context,
	request *v2.TaskNoteCreatePayload,
	opts ...option.RequestOption,
) (*v2.NoteResponse, error) {
	response, err := c.WithRawResponse.CreateTaskNote(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
