// Code generated by Fern. DO NOT EDIT.

package loans

import (
	context "context"

	v2 "github.com/voltariafinance/go-sdk/v2"
	core "github.com/voltariafinance/go-sdk/v2/core"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	option "github.com/voltariafinance/go-sdk/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve all loans associated with your partner account. Supports optional filtering by client ID.
func (c *Client) ListLoans(
	ctx context.Context,
	request *v2.ListLoansRequest,
	opts ...option.RequestOption,
) (*v2.PaginatedResponseLoanResponseWithClientInfo, error) {
	response, err := c.WithRawResponse.ListLoans(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new loan for an approved client with an active credit limit.
func (c *Client) CreateLoan(
	ctx context.Context,
	request *v2.LoanCreatePayload,
	opts ...option.RequestOption,
) (*v2.LoanResponseWithInstallments, error) {
	response, err := c.WithRawResponse.CreateLoan(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve detailed information about a specific loan by its loan ID.
func (c *Client) GetLoanByID(
	ctx context.Context,
	request *v2.GetLoanByIDRequest,
	opts ...option.RequestOption,
) (*v2.LoanResponseWithInstallments, error) {
	response, err := c.WithRawResponse.GetLoanByID(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a loan by ID. Only loans with 'pending' status can be deleted.
func (c *Client) DeleteLoan(
	ctx context.Context,
	request *v2.DeleteLoanRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.DeleteLoan(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create multiple loans in a single request. Processing happens asynchronously. Returns a task ID for tracking progress.
func (c *Client) CreateBulkLoans(
	ctx context.Context,
	request *v2.BulkLoanCreatePayload,
	opts ...option.RequestOption,
) (*v2.BulkLoanTaskResponse, error) {
	response, err := c.WithRawResponse.CreateBulkLoans(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Check the status of a bulk loan creation task and retrieve results when completed.
func (c *Client) GetBulkLoanStatus(
	ctx context.Context,
	request *v2.GetBulkLoanStatusRequest,
	opts ...option.RequestOption,
) (*v2.BulkLoanTaskStatus, error) {
	response, err := c.WithRawResponse.GetBulkLoanStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Mark a loan as defaulted, recording the default date and the amount recovered from selling it. Defaults the loan's active and overdue installments and updates the loan status accordingly.
func (c *Client) SetLoanDefault(
	ctx context.Context,
	request *v2.LoanDefaultPayload,
	opts ...option.RequestOption,
) (*v2.LoanResponseWithInstallments, error) {
	response, err := c.WithRawResponse.SetLoanDefault(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
