// Code generated by Fern. DO NOT EDIT.

package drawdowns

import (
	context "context"
	http "net/http"

	v2 "github.com/voltariafinance/go-sdk/v2"
	core "github.com/voltariafinance/go-sdk/v2/core"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	option "github.com/voltariafinance/go-sdk/v2/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) ListDrawdowns(
	ctx context.Context,
	request *v2.ListDrawdownsRequest,
	opts ...option.RequestOption,
) (*core.Response[*v2.PaginatedResponseDrawdownResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := baseURL + "/v2/drawdowns"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *v2.PaginatedResponseDrawdownResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.PaginatedResponseDrawdownResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateDrawdownRequest(
	ctx context.Context,
	request *v2.DrawdownCreatePayload,
	opts ...option.RequestOption,
) (*core.Response[*v2.DrawdownResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := baseURL + "/v2/drawdowns"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *v2.DrawdownResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.DrawdownResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListDrawdownChecklists(
	ctx context.Context,
	request *v2.ListDrawdownChecklistsRequest,
	opts ...option.RequestOption,
) (*core.Response[*v2.PaginatedResponseDrawdownChecklistResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/drawdowns/%v/checklists",
		request.DrawdownID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *v2.PaginatedResponseDrawdownChecklistResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.PaginatedResponseDrawdownChecklistResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
