// Code generated by Fern. DO NOT EDIT.

package webhooks

import (
	context "context"

	v2 "github.com/voltariafinance/go-sdk/v2"
	core "github.com/voltariafinance/go-sdk/v2/core"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	option "github.com/voltariafinance/go-sdk/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// List all webhook subscriptions for your partner account.
func (c *Client) ListWebhookSubscriptions(
	ctx context.Context,
	request *v2.ListWebhookSubscriptionsRequest,
	opts ...option.RequestOption,
) (*v2.PaginatedResponseWebhookSubscriptionResponse, error) {
	response, err := c.WithRawResponse.ListWebhookSubscriptions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new webhook subscription for a specific event type.
func (c *Client) CreateWebhookSubscription(
	ctx context.Context,
	request *v2.WebhookCreatePayload,
	opts ...option.RequestOption,
) (*v2.WebhookSubscriptionResponse, error) {
	response, err := c.WithRawResponse.CreateWebhookSubscription(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve details for a specific webhook subscription with its webhook ID.
func (c *Client) GetWebhookSubscription(
	ctx context.Context,
	request *v2.GetWebhookSubscriptionRequest,
	opts ...option.RequestOption,
) (*v2.WebhookSubscriptionResponse, error) {
	response, err := c.WithRawResponse.GetWebhookSubscription(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update a webhook subscription with its specific webhook ID.
func (c *Client) UpdateWebhookSubscription(
	ctx context.Context,
	request *v2.WebhookUpdatePayload,
	opts ...option.RequestOption,
) (*v2.WebhookSubscriptionResponse, error) {
	response, err := c.WithRawResponse.UpdateWebhookSubscription(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a specific webhook subscription.
func (c *Client) DeleteWebhookSubscription(
	ctx context.Context,
	request *v2.DeleteWebhookSubscriptionRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.DeleteWebhookSubscription(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve all webhook logs linked to your partner account.
func (c *Client) ListWebhookLogs(
	ctx context.Context,
	request *v2.ListWebhookLogsRequest,
	opts ...option.RequestOption,
) (*v2.PaginatedResponseWebhookLogResponse, error) {
	response, err := c.WithRawResponse.ListWebhookLogs(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
