// Code generated by Fern. DO NOT EDIT.

package investors

import (
	context "context"

	v2 "github.com/voltariafinance/go-sdk/v2"
	core "github.com/voltariafinance/go-sdk/v2/core"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	option "github.com/voltariafinance/go-sdk/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve all clients with at least one loan funded by this investor.
func (c *Client) InvestorListClients(
	ctx context.Context,
	request *v2.InvestorListClientsRequest,
	opts ...option.RequestOption,
) (*v2.PaginatedResponseClientInvestorResponse, error) {
	response, err := c.WithRawResponse.InvestorListClients(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a specific client that has a loan funded by this investor.
func (c *Client) InvestorGetClient(
	ctx context.Context,
	request *v2.InvestorGetClientRequest,
	opts ...option.RequestOption,
) (*v2.ClientInvestorResponse, error) {
	response, err := c.WithRawResponse.InvestorGetClient(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve all loans funded by the current investor.
func (c *Client) InvestorListLoans(
	ctx context.Context,
	request *v2.InvestorListLoansRequest,
	opts ...option.RequestOption,
) (*v2.PaginatedResponseLoanInvestorResponse, error) {
	response, err := c.WithRawResponse.InvestorListLoans(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a specific loan funded by the current investor, with its installments.
func (c *Client) InvestorGetLoan(
	ctx context.Context,
	request *v2.InvestorGetLoanRequest,
	opts ...option.RequestOption,
) (*v2.LoanResponseWithInstallments, error) {
	response, err := c.WithRawResponse.InvestorGetLoan(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve all installments for loans funded by the current investor.
func (c *Client) InvestorListInstallments(
	ctx context.Context,
	request *v2.InvestorListInstallmentsRequest,
	opts ...option.RequestOption,
) (*v2.PaginatedResponseInstallmentResponseWithClientInfo, error) {
	response, err := c.WithRawResponse.InvestorListInstallments(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a specific installment for a loan funded by the current investor.
func (c *Client) InvestorGetInstallment(
	ctx context.Context,
	request *v2.InvestorGetInstallmentRequest,
	opts ...option.RequestOption,
) (*v2.InstallmentResponse, error) {
	response, err := c.WithRawResponse.InvestorGetInstallment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve all repayment logs for loans funded by the current investor.
func (c *Client) InvestorListRepayments(
	ctx context.Context,
	request *v2.InvestorListRepaymentsRequest,
	opts ...option.RequestOption,
) (*v2.PaginatedResponseRepaymentResponseWithClientInfo, error) {
	response, err := c.WithRawResponse.InvestorListRepayments(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
