// Code generated by Fern. DO NOT EDIT.

package investors

import (
	context "context"
	http "net/http"

	v2 "github.com/voltariafinance/go-sdk/v2"
	core "github.com/voltariafinance/go-sdk/v2/core"
	internal "github.com/voltariafinance/go-sdk/v2/internal"
	option "github.com/voltariafinance/go-sdk/v2/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) InvestorListClients(
	ctx context.Context,
	request *v2.InvestorListClientsRequest,
	opts ...option.RequestOption,
) (*core.Response[*v2.PaginatedResponseClientInvestorResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := baseURL + "/v2/investors/clients"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *v2.PaginatedResponseClientInvestorResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.PaginatedResponseClientInvestorResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InvestorGetClient(
	ctx context.Context,
	request *v2.InvestorGetClientRequest,
	opts ...option.RequestOption,
) (*core.Response[*v2.ClientInvestorResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/investors/clients/%v",
		request.ClientID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *v2.ClientInvestorResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.ClientInvestorResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InvestorListLoans(
	ctx context.Context,
	request *v2.InvestorListLoansRequest,
	opts ...option.RequestOption,
) (*core.Response[*v2.PaginatedResponseLoanInvestorResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := baseURL + "/v2/investors/loans"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *v2.PaginatedResponseLoanInvestorResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.PaginatedResponseLoanInvestorResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InvestorGetLoan(
	ctx context.Context,
	request *v2.InvestorGetLoanRequest,
	opts ...option.RequestOption,
) (*core.Response[*v2.LoanResponseWithInstallments], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/investors/loans/%v",
		request.LoanID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *v2.LoanResponseWithInstallments
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.LoanResponseWithInstallments]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InvestorListInstallments(
	ctx context.Context,
	request *v2.InvestorListInstallmentsRequest,
	opts ...option.RequestOption,
) (*core.Response[*v2.PaginatedResponseInstallmentResponseWithClientInfo], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := baseURL + "/v2/investors/installments"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *v2.PaginatedResponseInstallmentResponseWithClientInfo
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.PaginatedResponseInstallmentResponseWithClientInfo]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InvestorGetInstallment(
	ctx context.Context,
	request *v2.InvestorGetInstallmentRequest,
	opts ...option.RequestOption,
) (*core.Response[*v2.InstallmentResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/investors/installments/%v",
		request.InstallmentID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *v2.InstallmentResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.InstallmentResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InvestorListRepayments(
	ctx context.Context,
	request *v2.InvestorListRepaymentsRequest,
	opts ...option.RequestOption,
) (*core.Response[*v2.PaginatedResponseRepaymentResponseWithClientInfo], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.sandbox.voltaria.io",
	)
	endpointURL := baseURL + "/v2/investors/repayments"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *v2.PaginatedResponseRepaymentResponseWithClientInfo
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(v2.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*v2.PaginatedResponseRepaymentResponseWithClientInfo]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
